package org.apache.cayenne.testdo.inheritance.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.inheritance.DirectToSubEntity;
import org.apache.cayenne.testdo.inheritance.SubEntity;

/**
 * Class _DirectToSubEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DirectToSubEntity extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<DirectToSubEntity> SELF = PropertyFactory.createSelf(DirectToSubEntity.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "DirectToSubEntity", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final ListProperty<SubEntity> SUB_ENTITIES = PropertyFactory.createList("subEntities", SubEntity.class);


    protected Object subEntities;

    public void addToSubEntities(SubEntity obj) {
        addToManyTarget("subEntities", obj, true);
    }

    public void removeFromSubEntities(SubEntity obj) {
        removeToManyTarget("subEntities", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<SubEntity> getSubEntities() {
        return (List<SubEntity>)readProperty("subEntities");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "subEntities":
                return this.subEntities;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "subEntities":
                this.subEntities = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.subEntities);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.subEntities = in.readObject();
    }

}
