package org.apache.cayenne.testdo.mt.auto;

/** Class _MtDeleteDeny was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _MtDeleteDeny extends org.apache.cayenne.CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String DENY_PROPERTY = "deny";

    public static final String DELETE_DENY_ID_PK_COLUMN = "DELETE_DENY_ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setDeny(org.apache.cayenne.testdo.mt.MtDeleteRule deny) {
        setToOneTarget("deny", deny, true);
    }

    public org.apache.cayenne.testdo.mt.MtDeleteRule getDeny() {
        return (org.apache.cayenne.testdo.mt.MtDeleteRule)readProperty("deny");
    } 
    
    
}
