package org.apache.cayenne.crypto.db.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.crypto.db.Table6;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;

/**
 * Class _Table6 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Table6 extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Table6> SELF = PropertyFactory.createSelf(Table6.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "Table6", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final NumericProperty<Long> CRYPTO_INT1 = PropertyFactory.createNumeric("cryptoInt1", Long.class);
    public static final NumericProperty<Integer> CRYPTO_INT4 = PropertyFactory.createNumeric("cryptoInt4", Integer.class);

    protected Long cryptoInt1;
    protected Integer cryptoInt4;


    public void setCryptoInt1(long cryptoInt1) {
        beforePropertyWrite("cryptoInt1", this.cryptoInt1, cryptoInt1);
        this.cryptoInt1 = cryptoInt1;
    }

    public long getCryptoInt1() {
        beforePropertyRead("cryptoInt1");
        if(this.cryptoInt1 == null) {
            return 0;
        }
        return this.cryptoInt1;
    }

    public void setCryptoInt4(int cryptoInt4) {
        beforePropertyWrite("cryptoInt4", this.cryptoInt4, cryptoInt4);
        this.cryptoInt4 = cryptoInt4;
    }

    public int getCryptoInt4() {
        beforePropertyRead("cryptoInt4");
        if(this.cryptoInt4 == null) {
            return 0;
        }
        return this.cryptoInt4;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "cryptoInt1":
                return this.cryptoInt1;
            case "cryptoInt4":
                return this.cryptoInt4;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "cryptoInt1":
                this.cryptoInt1 = (Long)val;
                break;
            case "cryptoInt4":
                this.cryptoInt4 = (Integer)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.cryptoInt1);
        out.writeObject(this.cryptoInt4);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.cryptoInt1 = (Long)in.readObject();
        this.cryptoInt4 = (Integer)in.readObject();
    }

}
