package org.apache.cayenne.crypto.db.auto;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.crypto.db.Table8;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

/**
 * Class _Table8 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Table8 extends PersistentObject {

    public static final SelfProperty<Table8> SELF = PropertyFactory.createSelf(Table8.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "Table8", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final StringProperty<String> CRYPTO_STRING = PropertyFactory.createString("cryptoString", String.class);

    protected String cryptoString;


    public void setCryptoString(String cryptoString) {
        beforePropertyWrite("cryptoString", this.cryptoString, cryptoString);
        this.cryptoString = cryptoString;
    }

    public String getCryptoString() {
        beforePropertyRead("cryptoString");
        return this.cryptoString;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "cryptoString":
                return this.cryptoString;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "cryptoString":
                this.cryptoString = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
