package org.apache.cayenne.testdo.weighted_sort.auto;

import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.weighted_sort.SortDep;
import org.apache.cayenne.testdo.weighted_sort.SortRoot;

/**
 * Class _SortRoot was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SortRoot extends PersistentObject {

    public static final SelfProperty<SortRoot> SELF = PropertyFactory.createSelf(SortRoot.class);

    public static final NumericIdProperty<Long> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "SortRoot", Long.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final ListProperty<SortDep> DEPS = PropertyFactory.createList("deps", SortDep.class);


    protected Object deps;

    public void addToDeps(SortDep obj) {
        addToManyTarget("deps", obj, true);
    }

    public void removeFromDeps(SortDep obj) {
        removeToManyTarget("deps", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<SortDep> getDeps() {
        return (List<SortDep>)readProperty("deps");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "deps":
                return this.deps;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "deps":
                this.deps = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
