package org.apache.cayenne.testdo.relationships_flattened.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.relationships_flattened.FlattenedTest1;
import org.apache.cayenne.testdo.relationships_flattened.FlattenedTest3;

/**
 * Class _FlattenedTest2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FlattenedTest2 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String FT2_ID_PK_COLUMN = "FT2_ID";

    public static final Property<String> NAME = new Property<>("name");
    public static final Property<List<FlattenedTest3>> FT3ARRAY = new Property<>("ft3Array");
    public static final Property<FlattenedTest1> TO_FT1 = new Property<>("toFT1");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToFt3Array(FlattenedTest3 obj) {
        addToManyTarget("ft3Array", obj, true);
    }
    public void removeFromFt3Array(FlattenedTest3 obj) {
        removeToManyTarget("ft3Array", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FlattenedTest3> getFt3Array() {
        return (List<FlattenedTest3>)readProperty("ft3Array");
    }


    public void setToFT1(FlattenedTest1 toFT1) {
        setToOneTarget("toFT1", toFT1, true);
    }

    public FlattenedTest1 getToFT1() {
        return (FlattenedTest1)readProperty("toFT1");
    }


}
