package org.apache.cayenne.testdo.inheritance_flat.auto;

import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.inheritance_flat.Role;
import org.apache.cayenne.testdo.inheritance_flat.User;
import org.apache.cayenne.testdo.inheritance_flat.UserProperties;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends Role {

    public static final SelfProperty<User> SELF = PropertyFactory.createSelf(User.class);

    public static final String ID_PK_COLUMN = "id";

    public static final EntityProperty<UserProperties> USER_PROPERTIES = PropertyFactory.createEntity("userProperties", UserProperties.class);


    protected Object userProperties;

    public void setUserProperties(UserProperties userProperties) {
        setToOneTarget("userProperties", userProperties, true);
    }

    public UserProperties getUserProperties() {
        return (UserProperties)readProperty("userProperties");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "userProperties":
                return this.userProperties;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "userProperties":
                this.userProperties = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
