package org.apache.cayenne.testdo.inheritance_vertical.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical.IvImpl;
import org.apache.cayenne.testdo.inheritance_vertical.IvImplWithLock;

import java.util.List;

/**
 * Class _IvOther was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvOther extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<IvImpl>> IMPLS = Property.create("impls", List.class);
    public static final Property<List<IvImplWithLock>> IMPLS_WITH_LOCK = Property.create("implsWithLock", List.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToImpls(IvImpl obj) {
        addToManyTarget("impls", obj, true);
    }
    public void removeFromImpls(IvImpl obj) {
        removeToManyTarget("impls", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<IvImpl> getImpls() {
        return (List<IvImpl>)readProperty("impls");
    }

    public void addToImplsWithLock(IvImplWithLock obj) {
        addToManyTarget("implsWithLock", obj, true);
    }
    public void removeFromImplsWithLock(IvImplWithLock obj) {
        removeToManyTarget("implsWithLock", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<IvImplWithLock> getImplsWithLock() {
        return (List<IvImplWithLock>)readProperty("implsWithLock");
    }


}
