/*****************************************************************
 *   Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 ****************************************************************/

package org.apache.cayenne.testdo.join.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.testdo.join.PaintingJoinExp;

/**
 * Class _PaintingInfoJoinExp was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PaintingInfoJoinExp extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String INFO_ID_PK_COLUMN = "INFO_ID";

    public static final NumericProperty<Integer> INFO_JOIN_ID = PropertyFactory.createNumeric("infoJoinId", Integer.class);
    public static final StringProperty<String> INFO = PropertyFactory.createString("info", String.class);
    public static final EntityProperty<PaintingJoinExp> TO_PAINTING = PropertyFactory.createEntity("toPainting", PaintingJoinExp.class);

    protected Integer infoJoinId;
    protected String info;

    protected Object toPainting;

    public void setInfoJoinId(int infoJoinId) {
        beforePropertyWrite("infoJoinId", this.infoJoinId, infoJoinId);
        this.infoJoinId = infoJoinId;
    }

    public int getInfoJoinId() {
        beforePropertyRead("infoJoinId");
        if(this.infoJoinId == null) {
            return 0;
        }
        return this.infoJoinId;
    }

    public void setInfo(String info) {
        beforePropertyWrite("info", this.info, info);
        this.info = info;
    }

    public String getInfo() {
        beforePropertyRead("info");
        return this.info;
    }

    public PaintingJoinExp getToPainting() {
        return (PaintingJoinExp)readProperty("toPainting");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "infoJoinId":
                return this.infoJoinId;
            case "info":
                return this.info;
            case "toPainting":
                return this.toPainting;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "infoJoinId":
                this.infoJoinId = (Integer)val;
                break;
            case "info":
                this.info = (String)val;
                break;
            case "toPainting":
                this.toPainting = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.infoJoinId);
        out.writeObject(this.info);
        out.writeObject(this.toPainting);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.infoJoinId = (Integer)in.readObject();
        this.info = (String)in.readObject();
        this.toPainting = in.readObject();
    }

}
