<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~    https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<!--
	Cayenne entity map schema
	Defines format of Cayenne DataMap XML files (*.map.xml).  DataMap files contain
	the metadata needed for Cayenne object-relational features. Multiple DataMaps
	are usually combined in one shared namespace, so the elements of the DataMap
	may reference objects from other DataMaps.
-->
<xs:schema targetNamespace="http://cayenne.apache.org/schema/14/dataMap"
	xmlns:cay="http://cayenne.apache.org/schema/14/dataMap"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="14">
	<xs:element name="dataMap">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embeddable"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:procedure"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:dbEntity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:objEntity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:dbRelationship"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:objRelationship"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="cay:objectQuery"/>
					<xs:element ref="cay:sqlQuery"/>
					<xs:element ref="cay:procedureQuery"/>
				</xs:choice>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="defaultLockType">
				<xs:annotation>
					<xs:documentation>A lock type of the new ObjEntities created in the DataMap.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="optimistic"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="defaultPackage" type="xs:string">
				<xs:annotation>
					<xs:documentation>A Java package of the classes of the new ObjEntities and Embeddables created in the DataMap.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="defaultCatalog" type="xs:string">
				<xs:annotation>
					<xs:documentation>A database catalog of the new DbEntities and Procedures created in the DataMap.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="defaultSchema" type="xs:string">
				<xs:annotation>
					<xs:documentation>A database schema of the new DbEntities and Procedures created in the DataMap.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="defaultSuperclass" type="xs:string">
				<xs:annotation>
					<xs:documentation>A Java superclass of the classes of the new ObjEntities created in the DataMap.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="quoteSqlIdentifiers" type="xs:boolean" default="false">
				<xs:annotation>
					<xs:documentation>Defines whether the names of the tables and columns of the DataMap are quoted in the generated SQL.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbEntity">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="cay:dbAttribute"/>
				<xs:element minOccurs="0" ref="cay:dbKeyGenerator"/>

				<!-- Qualifier for DB Entity -->
				<xs:element minOccurs="0" ref="cay:qualifier"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbAttribute">
		<xs:annotation>
			<xs:documentation>A database column.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="mandatory" type="xs:boolean"/>
			<xs:attribute name="primaryKey" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>If true, the value of attribute is unique and used as a primary key identifier.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="generated" type="xs:boolean"/>
			<xs:attribute name="length" type="xs:integer"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="scale" type="xs:integer"/>
			<xs:attribute name="attributePrecision" type="xs:integer"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="objEntity">
		<xs:annotation>
			<xs:documentation>A persistent Java class managed by Cayenne.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:qualifier"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embeddedAttribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:objAttribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:attributeOverride"/>

				<!--  Callbacks -->
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postAdd"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:prePersist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postPersist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:preUpdate"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postUpdate"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:preRemove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postRemove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:postLoad"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" type="xs:string"/>
			<xs:attribute name="abstract" type="xs:boolean"/>
			<xs:attribute name="readOnly" type="xs:boolean"/>
			<xs:attribute name="dbEntityName" type="xs:string"/>
			<xs:attribute name="lockType" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="superClassName" type="xs:string"/>
			<xs:attribute name="superEntityName" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="qualifier" type="xs:string"/>

	<xs:element name="objAttribute">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="dbAttributePath" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="lazy" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="attributeOverride">
		<xs:complexType>
			<xs:attribute name="dbAttributePath" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="type" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="dbRelationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="cay:dbAttributePair"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="toDependentPK" type="xs:boolean"/>
			<xs:attribute name="toMany" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="dbAttributePair">
		<xs:complexType>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="objRelationship">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="dbRelationshipPath" use="required" type="xs:string"/>
			<xs:attribute name="deleteRule" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="collectionType" type="xs:string"/>
			<xs:attribute name="mapKey" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="objectQuery">
		<xs:annotation>
			<xs:documentation>A named selecting query expressed in terms of object model using Cayenne QL.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:ql"/>
				<xs:element minOccurs="0" ref="cay:cacheGroup"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attributeGroup ref="cay:querySettings"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="sqlQuery">
		<xs:annotation>
			<xs:documentation>A named query expressed in SQL terms</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:sql"/>
				<xs:element minOccurs="0" ref="cay:cacheGroup"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:prefetch"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="root" type="xs:string"/>
			<xs:attribute name="rootName" type="xs:string"/>
			<xs:attributeGroup ref="cay:querySettings"/>
			<xs:attribute name="columnNameCapitalization" type="cay:columnNameCapitalization"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="procedureQuery">
		<xs:annotation>
			<xs:documentation>A named query that calls a stored procedure.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:cacheGroup"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="root" type="xs:string"/>
			<xs:attribute name="rootName" type="xs:string"/>
			<xs:attribute name="resultEntity" type="xs:string"/>
			<xs:attributeGroup ref="cay:querySettings"/>
			<xs:attribute name="fetchLimit" type="xs:nonNegativeInteger">
				<xs:annotation>
					<xs:documentation>A max number of rows fetched by a query.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="fetchOffset" type="xs:nonNegativeInteger">
				<xs:annotation>
					<xs:documentation>A number of rows skipped at the start of a query result.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="columnNameCapitalization" type="cay:columnNameCapitalization"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="cacheGroup" type="xs:string">
		<xs:annotation>
			<xs:documentation>A name of the cache group of a query used for cache configuration and invalidation purposes.</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:attributeGroup name="querySettings">
		<xs:attribute name="cacheStrategy">
			<xs:annotation>
				<xs:documentation>An optional cache strategy of a query.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="NO_CACHE"/>
					<xs:enumeration value="LOCAL_CACHE"/>
					<xs:enumeration value="LOCAL_CACHE_REFRESH"/>
					<xs:enumeration value="SHARED_CACHE"/>
					<xs:enumeration value="SHARED_CACHE_REFRESH"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="dataRows" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>Defines whether a query fetches DataRows instead of persistent objects.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="pageSize" type="xs:nonNegativeInteger">
			<xs:annotation>
				<xs:documentation>A page size of a query with a paginated result.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="statementFetchSize" type="xs:nonNegativeInteger">
			<xs:annotation>
				<xs:documentation>A fetch size of the JDBC statement of a query.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>

	<xs:simpleType name="columnNameCapitalization">
		<xs:annotation>
			<xs:documentation>A capitalization of the column names in a query result.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="DEFAULT"/>
			<xs:enumeration value="UPPER"/>
			<xs:enumeration value="LOWER"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="ql" type="xs:string">
		<xs:annotation>
			<xs:documentation>The query String of an "objectQuery" in the syntax of ObjectSelect.parse(..).</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="prefetch">
		<xs:annotation>
			<xs:documentation>A prefetch of a "sqlQuery" query.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="sql">
		<xs:annotation>
			<xs:documentation>Defines a SQL statement. Statements can be customized for different SQL dialects per DbAdapter class. If no adapter-specific statement is found, the one with no adapter label is used by default.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="adapterClass" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="embeddable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="embeddableAttribute" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="dbAttributeName" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embeddedAttribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded"
					ref="cay:embeddableAttributeOverride"/>
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embeddableAttributeOverride">
		<xs:complexType>
			<xs:attribute name="dbAttributePath" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="procedure">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="procedureParameter">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="length" type="xs:integer"/>
						<xs:attribute name="direction" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
			<xs:attribute name="returningValue" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="preUpdate">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postPersist">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postUpdate">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postAdd">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="prePersist">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postRemove">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="postLoad">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="preRemove">
		<xs:complexType>
			<xs:attribute name="methodName" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="dbKeyGenerator">
		<xs:annotation>
			<xs:documentation>Used to install the Automatic Sequence/Key Generation facility for dbEntity. This feature is intended for use with simple (non-compound) integral primary keys.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dbGeneratorType" type="xs:string">
					<xs:annotation>
						<xs:documentation>Specifies the Key Generation Method that will be employed
      'ORACLE'               - use Oracle's SEQUENCE
      'NAMED_SEQUENCE_TABLE' - use USER designated SEQUENCE TABLE. User specifies the name of a DBMS Table with the schema (sequence INT) which will be used to hold sequence values (not supported yet)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="dbGeneratorName" type="xs:string">
					<xs:annotation>
						<xs:documentation>For dbGeneratorType ORACLE this is the name of the ORACLE SEQUENCE to use. The SEQUENCE is assumed to already exist in the Database.
If this is dbGeneratorType NAMED_SEQUENCE_TABLE Key Generation, this specifies the name of the SEQUENCE TABLE to use. The NAMED_SEQUENCE_TABLE is assumed to already exist in the database.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="dbKeyCacheSize" type="xs:integer">
					<xs:annotation>
						<xs:documentation>Size of key cache. For dbGeneratorType ORACLE , this value MUST match the Oracle SEQUENCE  INCREMENT value.  If there is a mismatch between this value and the Oracle SEQUENCE INCREMENT value, then there will likely be duplicate key problems.
For dbGeneratorType NAMED_SEQUENCE_TABLE , this tells how many keys the Container will fetch in a single DBMS call.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
