// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.

include::../var.adoc[]

=== Setup

==== System Requirements

- Java: Cayenne runtime framework and CayenneModeler GUI tool are written in 100% Java, and run on any Java-compatible platform. Minimal required JDK version depends on the version of Cayenne you are using, as shown in the following table:

[#versionHistory.table.table-bordered]
.Cayenne Version History
[cols="2,3,2"]
|===
|Cayenne Version |Java Version |Status

|5.0
|Java 11 or newer
|Development

|4.2
|Java 1.8 or newer
|Stable

|4.1
|Java 1.8 -- Java 17
|Stable

|4.0
|Java 1.7 -- Java 11
|Aging

|3.0 / 3.1
|Java 1.5 -- Java 1.8
|Legacy

|1.2 / 2.0
|Java 1.4
|Legacy

|1.1
|Java 1.3
|Legacy
|===


- JDBC Driver: An appropriate DB-specific JDBC driver is needed to access the database. It can be included in the application or used in web container DataSource configuration.

- Third-party Libraries: Cayenne runtime framework has a minimal set of required and a few more optional dependencies on third-party open source packages. See <<Including Cayenne in a Project>> chapter for details.

[[runModeler]]
==== Running CayenneModeler

CayenneModeler GUI tool is intended to work with object relational mapping projects. While you can edit your XML by
hand, it is rarely needed, as the Modeler is a pretty advanced tool included in Cayenne distribution. To obtain
CayenneModeler, download Cayenne distribution archive from https://cayenne.apache.org/download.html matching the OS you
are using. Of course Java needs to be installed on the machine where you are going to run the Modeler.

- OS X distribution contains CayenneModeler.app at the root of the distribution disk image.
- Windows distribution contains CayenneModeler.exe file in the bin directory.
- Cross-platform distribution (targeting Linux, but as the name implies, compatible with any OS) contains a runnable
CayenneModeler.jar in the bin directory. It can be executed either by double-clicking, or if the environment is not
configured to execute jars, by running from command-line:

[source]
----
$ java -jar CayenneModeler.jar
----

A path to an existing Cayenne project file can be passed as the only argument to open the project on startup:

[source]
----
$ java -jar CayenneModeler.jar path/to/cayenne-project.xml
----

On macOS the same applies to the `.app` bundle:

[source]
----
$ open CayenneModeler.app --args path/to/cayenne-project.xml
----