// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.

=== ROP Deployment

==== Server Security Note

Recent versions of Tomcat and Jetty containers (e.g. Tomcat 6 and 7, Jetty 8) contain code
addressing a security concern related to "session fixation problem" by resetting the existing session ID of any request
that requires BASIC authentication. If ROP service is protected with declarative security
(see the ROP tutorial and the following chapters on security), this feature prevents the ROP client
from attaching to its session, resulting in `MissingSessionExceptions`.

To solve that you will need to either switch to an alternative security mechanism,
or disable "session fixation problem" protections of the container.
E.g. the later can be achieved in Tomcat 7 by adding the following `context.xml` file to the webapp's `META-INF/` directory:

[source, XML]
----
<Context>
    <Valve className="org.apache.catalina.authenticator.BasicAuthenticator"
            changeSessionIdOnAuthentication="false" />
</Context>
----

(The `<Valve>` tag can also be placed within the `<Context>` in any other locations used by Tomcat to load context configurations)

//==== Deploying ROP Client

//==== Security

