package org.apache.cayenne.testdo.json.auto;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.json.JsonOther;
import org.apache.cayenne.value.Json;

/**
 * Class _JsonOther was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _JsonOther extends PersistentObject {

    public static final SelfProperty<JsonOther> SELF = PropertyFactory.createSelf(JsonOther.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "JsonOther", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final BaseProperty<Json> DATA = PropertyFactory.createBase("data", Json.class);

    protected Json data;


    public void setData(Json data) {
        beforePropertyWrite("data", this.data, data);
        this.data = data;
    }

    public Json getData() {
        beforePropertyRead("data");
        return this.data;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "data":
                return this.data;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "data":
                this.data = (Json)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
