package org.apache.cayenne.testdo.relationship.auto;

import java.util.List;

/** Class _RelationshipHelper was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _RelationshipHelper extends org.apache.cayenne.CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String FKS_OF_DIFFERENT_TYPE_PROPERTY = "fksOfDifferentType";
    public static final String MEANIGFUL_FKS_PROPERTY = "meanigfulFKs";
    public static final String REFLEXIVE_AND_TO_ONE_ARRAY_PROPERTY = "reflexiveAndToOneArray";

    public static final String RELATIONSHIP_HELPER_ID_PK_COLUMN = "RELATIONSHIP_HELPER_ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void addToFksOfDifferentType(org.apache.cayenne.testdo.relationship.FkOfDifferentType obj) {
        addToManyTarget("fksOfDifferentType", obj, true);
    }
    public void removeFromFksOfDifferentType(org.apache.cayenne.testdo.relationship.FkOfDifferentType obj) {
        removeToManyTarget("fksOfDifferentType", obj, true);
    }
    public List getFksOfDifferentType() {
        return (List)readProperty("fksOfDifferentType");
    }
    
    
    public void addToMeanigfulFKs(org.apache.cayenne.testdo.relationship.MeaningfulFK obj) {
        addToManyTarget("meanigfulFKs", obj, true);
    }
    public void removeFromMeanigfulFKs(org.apache.cayenne.testdo.relationship.MeaningfulFK obj) {
        removeToManyTarget("meanigfulFKs", obj, true);
    }
    public List getMeanigfulFKs() {
        return (List)readProperty("meanigfulFKs");
    }
    
    
    public void addToReflexiveAndToOneArray(org.apache.cayenne.testdo.relationship.ReflexiveAndToOne obj) {
        addToManyTarget("reflexiveAndToOneArray", obj, true);
    }
    public void removeFromReflexiveAndToOneArray(org.apache.cayenne.testdo.relationship.ReflexiveAndToOne obj) {
        removeToManyTarget("reflexiveAndToOneArray", obj, true);
    }
    public List getReflexiveAndToOneArray() {
        return (List)readProperty("reflexiveAndToOneArray");
    }
    
    
}
