package org.apache.cayenne.testdo.inherit.auto;

import java.util.List;

import org.apache.cayenne.testdo.inherit.Department;
import org.apache.cayenne.testdo.inherit.Employee;

/**
 * Class _Manager was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Manager extends Employee {

    public static final String MANAGED_DEPARTMENTS_PROPERTY = "managedDepartments";

    public static final String PERSON_ID_PK_COLUMN = "PERSON_ID";

    public void addToManagedDepartments(Department obj) {
        addToManyTarget(MANAGED_DEPARTMENTS_PROPERTY, obj, true);
    }
    public void removeFromManagedDepartments(Department obj) {
        removeToManyTarget(MANAGED_DEPARTMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Department> getManagedDepartments() {
        return (List<Department>)readProperty(MANAGED_DEPARTMENTS_PROPERTY);
    }


}
