package org.apache.cayenne.testdo.things.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.GenericPersistentObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.testdo.things.Bag;
import org.apache.cayenne.testdo.things.Ball;
import org.apache.cayenne.testdo.things.Box;
import org.apache.cayenne.testdo.things.BoxInfo;
import org.apache.cayenne.testdo.things.Thing;

/**
 * Class _Box was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Box extends GenericPersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Box> SELF = PropertyFactory.createSelf(Box.class);

    public static final NumericIdProperty<Long> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "Box", Long.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final EntityProperty<Bag> BAG = PropertyFactory.createEntity("bag", Bag.class);
    public static final ListProperty<Ball> BALLS = PropertyFactory.createList("balls", Ball.class);
    public static final EntityProperty<BoxInfo> BOX_INFO = PropertyFactory.createEntity("boxInfo", BoxInfo.class);
    public static final ListProperty<Thing> THINGS = PropertyFactory.createList("things", Thing.class);

    protected String name;

    protected Object bag;
    protected Object balls;
    protected Object boxInfo;
    protected Object things;

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setBag(Bag bag) {
        setToOneTarget("bag", bag, true);
    }

    public Bag getBag() {
        return (Bag)readProperty("bag");
    }

    public void addToBalls(Ball obj) {
        addToManyTarget("balls", obj, true);
    }

    public void removeFromBalls(Ball obj) {
        removeToManyTarget("balls", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Ball> getBalls() {
        return (List<Ball>)readProperty("balls");
    }

    public void setBoxInfo(BoxInfo boxInfo) {
        setToOneTarget("boxInfo", boxInfo, true);
    }

    public BoxInfo getBoxInfo() {
        return (BoxInfo)readProperty("boxInfo");
    }

    public void addToThings(Thing obj) {
        addToManyTarget("things", obj, true);
    }

    public void removeFromThings(Thing obj) {
        removeToManyTarget("things", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Thing> getThings() {
        return (List<Thing>)readProperty("things");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "name":
                return this.name;
            case "bag":
                return this.bag;
            case "balls":
                return this.balls;
            case "boxInfo":
                return this.boxInfo;
            case "things":
                return this.things;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "name":
                this.name = (String)val;
                break;
            case "bag":
                this.bag = val;
                break;
            case "balls":
                this.balls = val;
                break;
            case "boxInfo":
                this.boxInfo = val;
                break;
            case "things":
                this.things = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.name);
        out.writeObject(this.bag);
        out.writeObject(this.balls);
        out.writeObject(this.boxInfo);
        out.writeObject(this.things);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.name = (String)in.readObject();
        this.bag = in.readObject();
        this.balls = in.readObject();
        this.boxInfo = in.readObject();
        this.things = in.readObject();
    }

}
