package org.apache.cayenne.testdo.relationship.auto;

import java.util.List;

/** Class _FlattenedTest1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _FlattenedTest1 extends org.apache.cayenne.CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String FT2ARRAY_PROPERTY = "ft2Array";
    public static final String FT3ARRAY_PROPERTY = "ft3Array";
    public static final String FT3OVER_COMPLEX_PROPERTY = "ft3OverComplex";

    public static final String FT1_ID_PK_COLUMN = "FT1_ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void addToFt2Array(org.apache.cayenne.testdo.relationship.FlattenedTest2 obj) {
        addToManyTarget("ft2Array", obj, true);
    }
    public void removeFromFt2Array(org.apache.cayenne.testdo.relationship.FlattenedTest2 obj) {
        removeToManyTarget("ft2Array", obj, true);
    }
    public List getFt2Array() {
        return (List)readProperty("ft2Array");
    }
    
    
    public void addToFt3Array(org.apache.cayenne.testdo.relationship.FlattenedTest3 obj) {
        addToManyTarget("ft3Array", obj, true);
    }
    public void removeFromFt3Array(org.apache.cayenne.testdo.relationship.FlattenedTest3 obj) {
        removeToManyTarget("ft3Array", obj, true);
    }
    public List getFt3Array() {
        return (List)readProperty("ft3Array");
    }
    
    
    public void addToFt3OverComplex(org.apache.cayenne.testdo.relationship.FlattenedTest3 obj) {
        addToManyTarget("ft3OverComplex", obj, true);
    }
    public void removeFromFt3OverComplex(org.apache.cayenne.testdo.relationship.FlattenedTest3 obj) {
        removeToManyTarget("ft3OverComplex", obj, true);
    }
    public List getFt3OverComplex() {
        return (List)readProperty("ft3OverComplex");
    }
    
    
}
