package org.apache.cayenne.testdo.many_to_many_joinTable_objEntity.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.testdo.many_to_many_joinTable_objEntity.Enrollments;

/**
 * Class _Course was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Course extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final ListProperty<Enrollments> ENROLLMENTS = PropertyFactory.createList("enrollments", Enrollments.class);


    protected Object enrollments;

    public void addToEnrollments(Enrollments obj) {
        addToManyTarget("enrollments", obj, true);
    }

    public void removeFromEnrollments(Enrollments obj) {
        removeToManyTarget("enrollments", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Enrollments> getEnrollments() {
        return (List<Enrollments>)readProperty("enrollments");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "enrollments":
                return this.enrollments;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "enrollments":
                this.enrollments = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.enrollments);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.enrollments = in.readObject();
    }

}
