package org.apache.cayenne.testdo.locking.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.locking.LockingHelper;
import org.apache.cayenne.testdo.locking.SimpleLockingTestEntity;

/**
 * Class _RelLockingTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RelLockingTestEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String REL_LOCKING_TEST_ID_PK_COLUMN = "REL_LOCKING_TEST_ID";

    public static final Property<String> NAME = new Property<>("name");
    public static final Property<List<LockingHelper>> LOCKING_HELPERS = new Property<>("lockingHelpers");
    public static final Property<SimpleLockingTestEntity> TO_SIMPLE_LOCKING_TEST = new Property<>("toSimpleLockingTest");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToLockingHelpers(LockingHelper obj) {
        addToManyTarget("lockingHelpers", obj, true);
    }
    public void removeFromLockingHelpers(LockingHelper obj) {
        removeToManyTarget("lockingHelpers", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<LockingHelper> getLockingHelpers() {
        return (List<LockingHelper>)readProperty("lockingHelpers");
    }


    public void setToSimpleLockingTest(SimpleLockingTestEntity toSimpleLockingTest) {
        setToOneTarget("toSimpleLockingTest", toSimpleLockingTest, true);
    }

    public SimpleLockingTestEntity getToSimpleLockingTest() {
        return (SimpleLockingTestEntity)readProperty("toSimpleLockingTest");
    }


}
