package org.apache.cayenne.testdo.locking.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _SoftTest was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SoftDelete extends CayenneDataObject {

    public static final String DELETED_PROPERTY = "deleted";
    public static final String NAME_PROPERTY = "name";

    public static final String ID_PK_COLUMN = "ID";

    public void setDeleted(Boolean deleted) {
        writeProperty(DELETED_PROPERTY, deleted);
    }
    public Boolean getDeleted() {
        return (Boolean)readProperty(DELETED_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    protected abstract void onPrePersist();

}
