package org.apache.cayenne.testdo.relationships_many_to_many_join.auto;

import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.testdo.relationships_many_to_many_join.Node;

/**
 * Class _Node was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Node extends PersistentObject {

    public static final SelfProperty<Node> SELF = PropertyFactory.createSelf(Node.class);

    public static final NumericIdProperty<Integer> NODE_ID_PK_PROPERTY = PropertyFactory.createNumericId("NODE_ID", "Node", Integer.class);
    public static final String NODE_ID_PK_COLUMN = "NODE_ID";

    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final NumericProperty<Integer> TYPE = PropertyFactory.createNumeric("type", Integer.class);
    public static final ListProperty<Node> PARENTS = PropertyFactory.createList("parents", Node.class);

    protected String name;
    protected int type;

    protected Object parents;

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setType(int type) {
        beforePropertyWrite("type", this.type, type);
        this.type = type;
    }

    public int getType() {
        beforePropertyRead("type");
        return this.type;
    }

    public void addToParents(Node obj) {
        addToManyTarget("parents", obj, true);
    }

    public void removeFromParents(Node obj) {
        removeToManyTarget("parents", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Node> getParents() {
        return (List<Node>)readProperty("parents");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "name":
                return this.name;
            case "type":
                return this.type;
            case "parents":
                return this.parents;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "name":
                this.name = (String)val;
                break;
            case "type":
                this.type = val == null ? 0 : (int)val;
                break;
            case "parents":
                this.parents = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
