package org.apache.cayenne.testdo.relationships_many_to_many_join.auto;

import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.relationships_many_to_many_join.Node;
import org.apache.cayenne.testdo.relationships_many_to_many_join.NodeB;

/**
 * Class _NodeB was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NodeB extends Node {

    public static final SelfProperty<NodeB> SELF = PropertyFactory.createSelf(NodeB.class);

    public static final NumericIdProperty<Integer> NODE_ID_PK_PROPERTY = PropertyFactory.createNumericId("NODE_ID", "NodeB", Integer.class);
    public static final String NODE_ID_PK_COLUMN = "NODE_ID";


}
