CREATE PROCEDURE cayenne_tst_upd_proc @paintingPrice INT AS 
BEGIN 
	BEGIN TRANSACTION UPDATE
	PAINTING SET ESTIMATED_PRICE = ESTIMATED_PRICE * 2 
	WHERE ESTIMATED_PRICE < @paintingPrice 
	COMMIT 
END
