// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.
==== SQLSelect and SQLExec

SQL is very powerful and allows to manipulate data in ways that can not always be described as a graph of related entities.
Cayenne acknowledges this fact and provides a facility to execute SQL, sometimes allowing to map results back to
persistent objects. `SQLSelect` and `SQLExec` are a pair of queries that allow to run native SQL. `SQLSelect` can be
used (as name suggests) to select custom data in form of entities, separate columns, collection of `DataRow` or Object[].
`SQLExec` is designed to execute any raw SQL code (e.g. updates, deletes, DDLs, etc.).

Both queries support advanced SQL templating, with variable substitution and special directives as described
<<sqlscripting,in the next chapter>>. Here we'll just provide a few simple examples:

[source, java]
----
// Selecting objects
List<Painting> paintings = SQLSelect
    .query(Painting.class, "SELECT * FROM PAINTING WHERE PAINTING_TITLE LIKE 'A%'")
    .upperColumnNames()
    .localCache()
    .limit(100)
    .select(context);

// Selecting scalar values
List<String> paintingNames = SQLSelect
    .scalarQuery(String.class, "SELECT PAINTING_TITLE FROM PAINTING WHERE ESTIMATED_PRICE > 100000")
    .select(context);

// Selecting DataRow with predefined types
List<DataRow> result = SQLSelect
    .dataRowQuery("SELECT * FROM ARTIST", Integer.class, String.class, LocalDateTime.class)
    .select(context);

// Selecting Object[] with predefined types
List<Object[]> result = SQLSelect
    .scalarQuery("SELECT * FROM ARTIST", Integer.class, String.class, LocalDateTime.class)
    .select(context);
----

And here is an example of how to use `SQLExec`:

[source, java]
----
int inserted = SQLExec
    .query("INSERT INTO ARTIST (ARTIST_ID, ARTIST_NAME) VALUES (55, 'Picasso')")
    .update(context);
----
