/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 5.0 */
package org.apache.cayenne.exp.parser;

public interface ExpressionParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTOR = 1;
  public int JJTAND = 2;
  public int JJTNOT = 3;
  public int JJTTRUE = 4;
  public int JJTFALSE = 5;
  public int JJTEQUAL = 6;
  public int JJTNOTEQUAL = 7;
  public int JJTLESSOREQUAL = 8;
  public int JJTLESS = 9;
  public int JJTGREATER = 10;
  public int JJTGREATEROREQUAL = 11;
  public int JJTLIKE = 12;
  public int JJTLIKEIGNORECASE = 13;
  public int JJTIN = 14;
  public int JJTBETWEEN = 15;
  public int JJTNOTLIKE = 16;
  public int JJTNOTLIKEIGNORECASE = 17;
  public int JJTNOTIN = 18;
  public int JJTNOTBETWEEN = 19;
  public int JJTLIST = 20;
  public int JJTSCALAR = 21;
  public int JJTBITWISEOR = 22;
  public int JJTBITWISEXOR = 23;
  public int JJTBITWISEAND = 24;
  public int JJTBITWISELEFTSHIFT = 25;
  public int JJTBITWISERIGHTSHIFT = 26;
  public int JJTADD = 27;
  public int JJTSUBTRACT = 28;
  public int JJTMULTIPLY = 29;
  public int JJTDIVIDE = 30;
  public int JJTBITWISENOT = 31;
  public int JJTNEGATE = 32;
  public int JJTCUSTOMFUNCTION = 33;
  public int JJTCONCAT = 34;
  public int JJTSUBSTRING = 35;
  public int JJTTRIM = 36;
  public int JJTLOWER = 37;
  public int JJTUPPER = 38;
  public int JJTLENGTH = 39;
  public int JJTLOCATE = 40;
  public int JJTABS = 41;
  public int JJTSQRT = 42;
  public int JJTMOD = 43;
  public int JJTASTERISK = 44;
  public int JJTCOUNT = 45;
  public int JJTAVG = 46;
  public int JJTMAX = 47;
  public int JJTMIN = 48;
  public int JJTSUM = 49;
  public int JJTCURRENTDATE = 50;
  public int JJTCURRENTTIME = 51;
  public int JJTCURRENTTIMESTAMP = 52;
  public int JJTEXTRACT = 53;
  public int JJTDISTINCT = 54;
  public int JJTNAMEDPARAMETER = 55;
  public int JJTOBJPATH = 56;
  public int JJTDBPATH = 57;
  public int JJTENUM = 58;
  public int JJTDBIDPATH = 59;


  public String[] jjtNodeName = {
    "void",
    "Or",
    "And",
    "Not",
    "True",
    "False",
    "Equal",
    "NotEqual",
    "LessOrEqual",
    "Less",
    "Greater",
    "GreaterOrEqual",
    "Like",
    "LikeIgnoreCase",
    "In",
    "Between",
    "NotLike",
    "NotLikeIgnoreCase",
    "NotIn",
    "NotBetween",
    "List",
    "Scalar",
    "BitwiseOr",
    "BitwiseXor",
    "BitwiseAnd",
    "BitwiseLeftShift",
    "BitwiseRightShift",
    "Add",
    "Subtract",
    "Multiply",
    "Divide",
    "BitwiseNot",
    "Negate",
    "CustomFunction",
    "Concat",
    "Substring",
    "Trim",
    "Lower",
    "Upper",
    "Length",
    "Locate",
    "Abs",
    "Sqrt",
    "Mod",
    "Asterisk",
    "Count",
    "Avg",
    "Max",
    "Min",
    "Sum",
    "CurrentDate",
    "CurrentTime",
    "CurrentTimestamp",
    "Extract",
    "Distinct",
    "NamedParameter",
    "ObjPath",
    "DbPath",
    "Enum",
    "DbIdPath",
  };
}
/* JavaCC - OriginalChecksum=d21da7d665d0ef7c43630d13a09f2c1d (do not edit this line) */
