/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */
/*****************************************************************
 *   Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 ****************************************************************/


package org.apache.cayenne.exp.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NULL = 38;
  /** RegularExpression Id. */
  int TRUE = 39;
  /** RegularExpression Id. */
  int FALSE = 40;
  /** RegularExpression Id. */
  int PROPERTY_PATH = 41;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;
  /** RegularExpression Id. */
  int LETTER = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int ESC = 47;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 49;
  /** RegularExpression Id. */
  int STRING_ESC = 50;
  /** RegularExpression Id. */
  int DOUBLE_QUOTED_STRING = 52;
  /** RegularExpression Id. */
  int INT_LITERAL = 53;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 54;
  /** RegularExpression Id. */
  int DEC_FLT = 55;
  /** RegularExpression Id. */
  int DEC_DIGITS = 56;
  /** RegularExpression Id. */
  int EXPONENT = 57;
  /** RegularExpression Id. */
  int FLT_SUFF = 58;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinSingleQuoteLiteral = 1;
  /** Lexical state. */
  int WithinDoubleQuoteLiteral = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"!\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<>\"",
    "\"<=\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"like\"",
    "\"likeIgnoreCase\"",
    "\"in\"",
    "\"(\"",
    "\")\"",
    "\"between\"",
    "\",\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"~\"",
    "\"$\"",
    "\"obj:\"",
    "\"db:\"",
    "\"enum:\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NULL>",
    "<TRUE>",
    "<FALSE>",
    "<PROPERTY_PATH>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<ESC>",
    "<token of kind 48>",
    "\"\\\'\"",
    "<STRING_ESC>",
    "<token of kind 51>",
    "\"\\\"\"",
    "<INT_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DEC_FLT>",
    "<DEC_DIGITS>",
    "<EXPONENT>",
    "<FLT_SUFF>",
  };

}
