package org.apache.cayenne.testdo.relationship.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.testdo.relationship.ToManyFkRoot;
import org.apache.cayenne.testdo.relationship.ToManyRoot2;

/**
 * Class _ToManyFkDep was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ToManyFkDep extends CayenneDataObject {

    public static final String DEP_ID_PROPERTY = "depId";
    public static final String NAME_PROPERTY = "name";
    public static final String ROOT_PROPERTY = "root";
    public static final String ROOT2_PROPERTY = "root2";

    public static final String DEP_ID_PK_COLUMN = "DEP_ID";
    public static final String OTHER_ID_PK_COLUMN = "OTHER_ID";

    public void setDepId(Integer depId) {
        writeProperty(DEP_ID_PROPERTY, depId);
    }
    public Integer getDepId() {
        return (Integer)readProperty(DEP_ID_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setRoot(ToManyFkRoot root) {
        setToOneTarget(ROOT_PROPERTY, root, true);
    }

    public ToManyFkRoot getRoot() {
        return (ToManyFkRoot)readProperty(ROOT_PROPERTY);
    }


    public void setRoot2(ToManyRoot2 root2) {
        setToOneTarget(ROOT2_PROPERTY, root2, true);
    }

    public ToManyRoot2 getRoot2() {
        return (ToManyRoot2)readProperty(ROOT2_PROPERTY);
    }


}
