// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.
=== Custom Queries

If a user needs some extra functionality not addressed by the existing set of Cayenne queries, he can write his own.
The only requirement is to implement `org.apache.cayenne.query.Query` interface.
E.g. to do something directly in the JDBC layer, you might implement `Query` like this:

[source,java,indent=0]
----
include::{java-examples}/customquery/MyQuery.java[tags=content]
----

To delegate the actual query execution to a standard Cayenne query, you may subclass `IndirectQuery`:


[source,java,indent=0]
----
include::{java-examples}/customquery/MyDelegatingQuery.java[tags=content]
----

In fact many internal Cayenne queries are `IndirectQueries`, delegating to `ObjectSelect` or `SQLTemplate`
after some preprocessing.