// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.
[[select]]
=== ObjectSelect

NOTE: `ObjectSelect` supersedes older `SelectQuery`. `SelectQuery` is deprecated since 4.2 and removed in 5.0.

==== Selecting objects

`ObjectSelect` is the most commonly used query in Cayenne applications. This may be the only query you will ever need.
It returns a list of persistent objects (or data rows) of a certain type specified in the query:

[source,java,indent=0]
----
include::{java-examples}/ObjectSelectTest.java[tags=selectAll]
----

This returned all rows in the _ARTIST_ table. If the logs were turned on, you might see the following SQL printed:

[source]
----
INFO: SELECT ARTIST_NAME, DATE_OF_BIRTH, ARTIST_ID FROM ARTIST | selected:5 time_ms:5
----

This SQL was generated by Cayenne from the `ObjectSelect` above.
`ObjectSelect` can have a qualifier to select only the data matching specific criteria.
Qualifier is simply an Expression (Expressions where discussed in the <<Expressions,previous chapter>>),
appended to the query using "where" method. If you only want artists whose name begins with 'Pablo',
you might use the following qualifier expression:

[source,java,indent=0]
----
include::{java-examples}/ObjectSelectTest.java[tags=where]
----

The SQL will look different this time:

[source]
----
INFO: SELECT ARTIST_NAME, DATE_OF_BIRTH, ARTIST_ID FROM ARTIST WHERE ARTIST_NAME LIKE ?
    | bind:[ARTIST_NAME:'Pablo%'] selected:1 time_ms:6
----

`ObjectSelect` allows to assemble qualifier from parts, using "and" and "or" method to chain them together:

[source,java,indent=0]
----
include::{java-examples}/ObjectSelectTest.java[tags=and]
----

To order the results of `ObjectSelect`, one or more orderings can be applied:

[source,java,indent=0]
----
include::{java-examples}/ObjectSelectTest.java[tags=orderBy]
----

There's a number of other useful methods in `ObjectSelect` that define what to select
and how to optimize database interaction (prefetching, caching, fetch offset and limit, pagination, etc.).
Some of them are discussed in separate chapters on caching and performance optimization.
Others are fairly self-explanatory. Please check the API docs for the full extent of the `ObjectSelect` features.

==== Selecting individual columns

`ObjectSelect` query can be used to fetch individual properties of objects via type-safe API:

[source,java,indent=0]
----
include::{java-examples}/ObjectSelectTest.java[tags=column]
----

And here is an example of selecting several properties. The result is a list of `Object[]`:

[source,java,indent=0]
----
include::{java-examples}/ObjectSelectTest.java[tags=columns]
----

==== Selecting using aggregate functions

ObjectSelect query supports usage of aggregate functions.
Most common variant of aggregation is selecting count of records, this can be done really easy:

[source,java,indent=0]
----
include::{java-examples}/ObjectSelectTest.java[tags=count]
----

But you can use aggregates in more cases, even combine selecting individual properties and aggregates:

[source,java,indent=0]
----
include::{java-examples}/ObjectSelectTest.java[tags=aggregates]
----

Here is generated `SQL` for this query:

[source, SQL]
----
SELECT DISTINCT a.ARTIST_NAME, a.DATE_OF_BIRTH, a.ARTIST_ID, COUNT(p.PAINTING_ID)
FROM ARTIST a JOIN PAINTING p ON a.ARTIST_ID = p.ARTIST_ID
WHERE a.ARTIST_NAME LIKE ?
GROUP BY a.ARTIST_NAME, a.DATE_OF_BIRTH, a.ARTIST_ID
HAVING (COUNT(p.PAINTING_ID) < ?)
ORDER BY COUNT(p.PAINTING_ID) DESC, a.ARTIST_NAME
----

==== Subqueries

Since Cayenne 4.2 `ObjectSelect` supports subqueries, and since 5.0 subqueries API is greatly improved.
Here is an example of a basic `NOT EXISTS` subquery:

[source,java,indent=0]
----
include::{java-examples}/ObjectSelectTest.java[tags=notExists]
----

And here's a generated `SQL`:

[source, SQL]
----
SELECT COUNT( *)
FROM ARTIST a
WHERE
    NOT EXISTS (SELECT p.PAINTING_ID
                FROM PAINTING p
                WHERE p.ARTIST_ID = a.ARTIST_ID
    )
----