package org.apache.cayenne.testdo.lob.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.lob.DistEntityRel;

/**
 * Class _DistEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DistEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<byte[]> FIELD = Property.create("field", byte[].class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<DistEntityRel>> DIST_REL = Property.create("distRel", List.class);

    protected byte[] field;
    protected String name;

    protected Object distRel;

    public void setField(byte[] field) {
        beforePropertyWrite("field", this.field, field);
        this.field = field;
    }

    public byte[] getField() {
        beforePropertyRead("field");
        return this.field;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void addToDistRel(DistEntityRel obj) {
        addToManyTarget("distRel", obj, true);
    }

    public void removeFromDistRel(DistEntityRel obj) {
        removeToManyTarget("distRel", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<DistEntityRel> getDistRel() {
        return (List<DistEntityRel>)readProperty("distRel");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "field":
                return this.field;
            case "name":
                return this.name;
            case "distRel":
                return this.distRel;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "field":
                this.field = (byte[])val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "distRel":
                this.distRel = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.field);
        out.writeObject(this.name);
        out.writeObject(this.distRel);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.field = (byte[])in.readObject();
        this.name = (String)in.readObject();
        this.distRel = in.readObject();
    }

}
