/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.cayenne.testdo.lob.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.lob.ClobTestRelation;

import java.util.List;

/**
 * Class _NClobTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NClobTestEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String NCLOB_COL_PROPERTY = "nclobCol";
    @Deprecated
    public static final String NCLOB_VALUE_PROPERTY = "nclobValue";

    public static final String NCLOB_TEST_ID_PK_COLUMN = "NCLOB_TEST_ID";

    public static final Property<String> NCLOB_COL = new Property<String>("nclobCol");
    public static final Property<List<ClobTestRelation>> NCLOB_VALUE = new Property<List<ClobTestRelation>>("nclobValue");

    public void setNclobCol(String nclobCol) {
        writeProperty("nclobCol", nclobCol);
    }
    public String getNclobCol() {
        return (String)readProperty("nclobCol");
    }

}
