package org.apache.art.auto;

/** Class _Gallery was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _Gallery extends org.apache.cayenne.CayenneDataObject {

    public static final String GALLERY_NAME_PROPERTY = "galleryName";
    public static final String EXHIBIT_ARRAY_PROPERTY = "exhibitArray";
    public static final String PAINTING_ARRAY_PROPERTY = "paintingArray";

    public static final String GALLERY_ID_PK_COLUMN = "GALLERY_ID";

    public void setGalleryName(String galleryName) {
        writeProperty("galleryName", galleryName);
    }
    public String getGalleryName() {
        return (String)readProperty("galleryName");
    }
    
    
    public void addToExhibitArray(org.apache.art.Exhibit obj) {
        addToManyTarget("exhibitArray", obj, true);
    }
    public void removeFromExhibitArray(org.apache.art.Exhibit obj) {
        removeToManyTarget("exhibitArray", obj, true);
    }
    public java.util.List getExhibitArray() {
        return (java.util.List)readProperty("exhibitArray");
    }
    
    
    public void addToPaintingArray(org.apache.art.Painting obj) {
        addToManyTarget("paintingArray", obj, true);
    }
    public void removeFromPaintingArray(org.apache.art.Painting obj) {
        removeToManyTarget("paintingArray", obj, true);
    }
    public java.util.List getPaintingArray() {
        return (java.util.List)readProperty("paintingArray");
    }
    
    
}
