package org.apache.art.auto;

/** Class _MixedPersistenceStrategy was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _MixedPersistenceStrategy extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String DETAILS_PROPERTY = "details";

    public static final String ID_PK_COLUMN = "ID";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void addToDetails(org.apache.art.MixedPersistenceStrategy2 obj) {
        addToManyTarget("details", obj, true);
    }
    public void removeFromDetails(org.apache.art.MixedPersistenceStrategy2 obj) {
        removeToManyTarget("details", obj, true);
    }
    public java.util.List getDetails() {
        return (java.util.List)readProperty("details");
    }
    
    
}
