package org.apache.art.auto;

/** Class _ROArtist was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _ROArtist extends org.apache.cayenne.CayenneDataObject {

    public static final String ARTIST_NAME_PROPERTY = "artistName";
    public static final String DATE_OF_BIRTH_PROPERTY = "dateOfBirth";
    public static final String PAINTING_ARRAY_PROPERTY = "paintingArray";

    public static final String ARTIST_ID_PK_COLUMN = "ARTIST_ID";

    public String getArtistName() {
        return (String)readProperty("artistName");
    }
    
    
    public java.sql.Date getDateOfBirth() {
        return (java.sql.Date)readProperty("dateOfBirth");
    }
    
    
    public void addToPaintingArray(org.apache.art.Painting obj) {
        addToManyTarget("paintingArray", obj, true);
    }
    public void removeFromPaintingArray(org.apache.art.Painting obj) {
        removeToManyTarget("paintingArray", obj, true);
    }
    public java.util.List getPaintingArray() {
        return (java.util.List)readProperty("paintingArray");
    }
    
    
}
