package org.apache.art.auto;

/** Class _CalendarEntity was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _CalendarEntity extends org.apache.cayenne.CayenneDataObject {

    public static final String CALENDAR_FIELD_PROPERTY = "calendarField";

    public static final String ID_PK_COLUMN = "ID";

    public void setCalendarField(java.util.Calendar calendarField) {
        writeProperty("calendarField", calendarField);
    }
    public java.util.Calendar getCalendarField() {
        return (java.util.Calendar)readProperty("calendarField");
    }
    
    
}
