package org.apache.cayenne.itest.cpa.defaults.auto;

/** Class _DefaultsTable2 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _DefaultsTable2 extends org.apache.cayenne.CayenneDataObject {

    public static final String TO_TABLE1_PROPERTY = "toTable1";

    public static final String ID_PK_COLUMN = "id";

    public void setToTable1(org.apache.cayenne.itest.cpa.defaults.DefaultsTable1 toTable1) {
        setToOneTarget("toTable1", toTable1, true);
    }

    public org.apache.cayenne.itest.cpa.defaults.DefaultsTable1 getToTable1() {
        return (org.apache.cayenne.itest.cpa.defaults.DefaultsTable1)readProperty("toTable1");
    } 
    
    
}
