package org.apache.cayenne.testdo.datetime.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalTime;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.datetime.LocalTimeTestEntity;

/**
 * Class _LocalTimeTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LocalTimeTestEntity extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<LocalTimeTestEntity> SELF = PropertyFactory.createSelf(LocalTimeTestEntity.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "LocalTimeTest", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final DateProperty<LocalTime> TIME = PropertyFactory.createDate("time", LocalTime.class);

    protected LocalTime time;


    public void setTime(LocalTime time) {
        beforePropertyWrite("time", this.time, time);
        this.time = time;
    }

    public LocalTime getTime() {
        beforePropertyRead("time");
        return this.time;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "time":
                return this.time;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "time":
                this.time = (LocalTime)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.time);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.time = (LocalTime)in.readObject();
    }

}
