package org.apache.cayenne.testdo.legacy_datetime.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Calendar;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.legacy_datetime.CalendarEntity;

/**
 * Class _CalendarEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CalendarEntity extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<CalendarEntity> SELF = PropertyFactory.createSelf(CalendarEntity.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "CalendarEntity", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final BaseProperty<Calendar> CALENDAR_FIELD = PropertyFactory.createBase("calendarField", Calendar.class);

    protected Calendar calendarField;


    public void setCalendarField(Calendar calendarField) {
        beforePropertyWrite("calendarField", this.calendarField, calendarField);
        this.calendarField = calendarField;
    }

    public Calendar getCalendarField() {
        beforePropertyRead("calendarField");
        return this.calendarField;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "calendarField":
                return this.calendarField;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "calendarField":
                this.calendarField = (Calendar)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.calendarField);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.calendarField = (Calendar)in.readObject();
    }

}
