package org.apache.cayenne.testdo.relationships_clob.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.relationships_clob.ClobMaster;

/**
 * Class _ClobDetail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ClobDetail extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CLOB_DETAIL_ID_PK_COLUMN = "CLOB_DETAIL_ID";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<ClobMaster> MASTER = Property.create("master", ClobMaster.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setMaster(ClobMaster master) {
        setToOneTarget("master", master, true);
    }

    public ClobMaster getMaster() {
        return (ClobMaster)readProperty("master");
    }


}
