package org.apache.cayenne.testdo.uuid.auto;

import java.util.UUID;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.uuid.UuidBinTestEntity;

/**
 * Class _UuidBinTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UuidBinTestEntity extends PersistentObject {

    public static final SelfProperty<UuidBinTestEntity> SELF = PropertyFactory.createSelf(UuidBinTestEntity.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "UuidBinTestEntity", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final BaseProperty<UUID> UUID = PropertyFactory.createBase("uuid", UUID.class);

    protected UUID uuid;


    public void setUuid(UUID uuid) {
        beforePropertyWrite("uuid", this.uuid, uuid);
        this.uuid = uuid;
    }

    public UUID getUuid() {
        beforePropertyRead("uuid");
        return this.uuid;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "uuid":
                return this.uuid;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "uuid":
                this.uuid = (UUID)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
