package org.apache.cayenne.testdo.uuid.auto;

import java.util.UUID;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.uuid.UuidPkEntity;

/**
 * Class _UuidPkEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UuidPkEntity extends PersistentObject {

    public static final SelfProperty<UuidPkEntity> SELF = PropertyFactory.createSelf(UuidPkEntity.class);

    public static final String ID_PK_COLUMN = "ID";

    public static final BaseProperty<UUID> ID = PropertyFactory.createBase("id", UUID.class);

    protected UUID id;


    public void setId(UUID id) {
        beforePropertyWrite("id", this.id, id);
        this.id = id;
    }

    public UUID getId() {
        beforePropertyRead("id");
        return this.id;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "id":
                return this.id;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "id":
                this.id = (UUID)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
