package org.apache.cayenne.testdo.inheritance_flat.auto;

import java.util.List;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_flat.GroupProperties;
import org.apache.cayenne.testdo.inheritance_flat.Role;
import org.apache.cayenne.testdo.inheritance_flat.User;

/**
 * Class _Group was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Group extends User {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<List<Role>> GROUP_MEMBERS = new Property<>("groupMembers");
    public static final Property<GroupProperties> GROUP_PROPERTIES = new Property<>("groupProperties");

    public void addToGroupMembers(Role obj) {
        addToManyTarget("groupMembers", obj, true);
    }
    public void removeFromGroupMembers(Role obj) {
        removeToManyTarget("groupMembers", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Role> getGroupMembers() {
        return (List<Role>)readProperty("groupMembers");
    }


    public void setGroupProperties(GroupProperties groupProperties) {
        setToOneTarget("groupProperties", groupProperties, true);
    }

    public GroupProperties getGroupProperties() {
        return (GroupProperties)readProperty("groupProperties");
    }


}
