package org.apache.cayenne.testdo.relationships_to_one_fk.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.relationships_to_one_fk.ToOneFK1;

/**
 * Class _ToOneFK2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ToOneFK2 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String TO_ONE_FK2_PK_PK_COLUMN = "TO_ONE_FK2_PK";

    public static final Property<ToOneFK1> TO_ONE_TO_FK = Property.create("toOneToFK", ToOneFK1.class);

    public void setToOneToFK(ToOneFK1 toOneToFK) {
        setToOneTarget("toOneToFK", toOneToFK, true);
    }

    public ToOneFK1 getToOneToFK() {
        return (ToOneFK1)readProperty("toOneToFK");
    }


}
