// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.

== New Features

=== New Dev Versioning Scheme

From now on a snapshot version of Cayenne is a constant value, so the dev version of 5.0 will always be 5.0-SNAPSHOT.
So you can always stay at the bleeding edge of development if needed.

[source,xml]
----
<dependency>
    <groupId>org.apache.cayenne</groupId>
    <artifactId>cayenne</artifactId>
    <version>5.0-SNAPSHOT</version>
</dependency>
----

=== New Class Generation UI

The new Class Generation UI in the Cayenne Modeler simplifies configuration, allows multiple `cgen` setups per project,
and includes a template editor.

Custom templates are now part of the project XML configuration and don't require separate setup in either Modeler, or Maven/Gradle plugins.

=== Improved `(not)exists` Queries

In most cases, you don’t need to deal with a subquery for `(not)exists` queries, as it is now directly supported by the Expression API.
That includes `Expression`, expression parser, and Property API.

This feature can handle any expression and spawn several sub-queries per expression if needed.

[source,java]
----
long count = ObjectSelect.query(Artist.class)
        .where(Artist.PAINTING_ARRAY.dot(Painting.PAINTING_TITLE).like("painting%").exists())
        .selectCount(context);
----

=== Improved SQL Support

`ANY` and `ALL` subqueries are now supported, as well as `case-when` expressions.

[source,java]
----
import static org.apache.cayenne.exp.ExpressionFactory.*;
// ...
Expression caseWhenExp = caseWhen(
                List.of((betweenExp("estimatedPrice", 0, 9)),
                        (betweenExp("estimatedPrice", 10, 20))),
                List.of((wrapScalarValue("low")),
                        (wrapScalarValue("high"))),
                wrapScalarValue("error"));
----

