package org.apache.cayenne.testdo.horizontalinherit.auto;

import org.apache.cayenne.testdo.horizontalinherit.AbstractSuperEntity;

/**
 * Class _SubEntity2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SubEntity2 extends AbstractSuperEntity {

    public static final String SUB_ENTITY_INT_ATTR_PROPERTY = "subEntityIntAttr";

    public static final String ID_PK_COLUMN = "id";

    public void setSubEntityIntAttr(int subEntityIntAttr) {
        writeProperty("subEntityIntAttr", subEntityIntAttr);
    }
    public int getSubEntityIntAttr() {
        Object value = readProperty("subEntityIntAttr");
        return (value != null) ? (Integer) value : 0;
    }

}
