package org.apache.cayenne.testdo.cay_2032.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.cay_2032.User;

/**
 * Class _Team was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Team extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String TEAM_ID_PK_COLUMN = "team_id";

    public static final Property<List<User>> TEAM_USERS = Property.create("teamUsers", List.class);


    protected Object teamUsers;

    public void addToTeamUsers(User obj) {
        addToManyTarget("teamUsers", obj, true);
    }

    public void removeFromTeamUsers(User obj) {
        removeToManyTarget("teamUsers", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<User> getTeamUsers() {
        return (List<User>)readProperty("teamUsers");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "teamUsers":
                return this.teamUsers;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "teamUsers":
                this.teamUsers = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.teamUsers);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.teamUsers = in.readObject();
    }

}
