package org.apache.cayenne.lifecycle.db.auto;

import org.apache.cayenne.GenericPersistentObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.lifecycle.db.SortRoot;

/**
 * Class _SortDep was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SortDep extends GenericPersistentObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final EntityProperty<SortRoot> ROOT = PropertyFactory.createEntity("root", SortRoot.class);

    public void setRoot(SortRoot root) {
        setToOneTarget("root", root, true);
    }

    public SortRoot getRoot() {
        return (SortRoot)readProperty("root");
    }


}
