// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.

== Appendix A. Configuration Properties

Note that the property names below are defined as constants in `org.apache.cayenne.configuration.Constants` interface.

[#configProperties]
* `cayenne.jdbc.driver[.domain_name.node_name]`
   defines a JDBC driver class to use when creating a DataSource. If domain name and optionally - node name are specified,
   the setting overrides DataSource info just for this domain/node. Otherwise the override is applied to all domains/nodes in the system.
    ** Default value: none, project DataNode configuration is used

* `cayenne.jdbc.url[.domain_name.node_name]`
    defines a DB URL to use when creating a DataSource. If domain name and optionally - node name are specified,
    the setting overrides DataSource info just for this domain/node. Otherwise the override is applied to all domains/nodes in the system.
    ** Default value: none, project DataNode configuration is used

* `cayenne.jdbc.username[.domain_name.node_name]`
   defines a DB user name to use when creating a DataSource. If domain name and optionally - node name are specified,
   the setting overrides DataSource info just for this domain/node. Otherwise the override is applied to all domains/nodes in the system.
    ** Possible values: any
    ** Default value: none, project DataNode configuration is used

* `cayenne.jdbc.password[.domain_name.node_name]`
   defines a DB password to use when creating a DataSource. If domain name and optionally - node name are specified,
   the setting overrides DataSource info just for this domain/node. Otherwise the override is applied to all domains/nodes in the system
    ** Default value: none, project DataNode configuration is used

* `cayenne.jdbc.min_connections[.domain_name.node_name]`
   defines the DB connection pool minimal size. If domain name and optionally - node name are specified, the setting
   overrides DataSource info just for this domain/node. Otherwise the override is applied to all domains/nodes in the system
    ** Default value: none, project DataNode configuration is used

* `cayenne.jdbc.max_connections[.domain_name.node_name]`
   defines the DB connection pool maximum size. If domain name and optionally - node name are specified, the setting
   overrides DataSource info just for this domain/node. Otherwise the override is applied to all domains/nodes in the system
    ** Default value: none, project DataNode configuration is used

* `cayenne.jdbc.max_wait`
   defines a maximum time in milliseconds that a connection request could
   wait in the connection queue. After this period expires, an exception
   will be thrown in the calling method. A value of zero will make the
   thread wait until a connection is available with no time out.
   ** Default value: 20 seconds

* `cayenne.jdbc.validation_query`
   defines a SQL string that returns some result. It will be used to
   validate connections in the pool.
   ** Default value: none

* `cayenne.querycache.size`
   An integer defining the maximum number of entries in the query cache. Note that not all QueryCache providers may respect this property.
   MapQueryCache uses it, but the rest would use alternative configuration methods.
    ** Possible values: any positive int value
    ** Default value: 2000

* `cayenne.DataRowStore.snapshot.size`
   defines snapshot cache max size
   ** Possible values: any positive int
   ** Default value: 10000

* `cayenne.contexts_sync_strategy`
   defines whether peer ObjectContexts should receive snapshot events after commits from other contexts. If true (_default_),
   the contexts would automatically synchronize their state with peers.
    ** Possible values: true, false
    ** Default value: false (since 4.1)

* `cayenne.object_retain_strategy`
   defines fetched objects retain strategy for ObjectContexts. When weak or soft strategy is used, objects retained by ObjectContext
   that have no local changes can potentially get garbage collected when JVM feels like doing it.
    ** Possible values: weak, soft, hard
    ** Default value: weak

* `cayenne.max_id_qualifier_size`
   defines a maximum number of ID qualifiers in the WHERE clause of queries that are generated for paginated queries and for DISJOINT_BY_ID prefetch processing.
   This is needed to avoid hitting WHERE clause size limitations and memory usage efficiency.
    ** Possible values: any positive int
    ** Default value: 10000

* `cayenne.external_tx`
   defines whether runtime should use external transactions.
    ** Possible values: true, false
    ** Default value: false

* `cayenne.query_execution_time_logging_threshold`
   defines the minimum number of milliseconds a query must run before it is logged.
   A value less than or equal to zero disables logging.
   ** Default value: 0

* `cayenne.domain.name`
   defines an optional name of the runtime DataDomain.
   If not specified, the name is inferred from the configuration name.
   ** Default value: none
