package org.apache.art.auto;

/** Class _BigDecimalEntity was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public abstract class _BigDecimalEntity extends org.apache.cayenne.CayenneDataObject {

    public static final String BIG_DECIMAL_FIELD_PROPERTY = "bigDecimalField";

    public static final String ID_PK_COLUMN = "ID";

    public void setBigDecimalField(java.math.BigDecimal bigDecimalField) {
        writeProperty("bigDecimalField", bigDecimalField);
    }
    public java.math.BigDecimal getBigDecimalField() {
        return (java.math.BigDecimal)readProperty("bigDecimalField");
    }
    
    
}
