package org.apache.cayenne.testdo.inheritance_horizontal.auto;

import org.apache.cayenne.testdo.inheritance_horizontal.AbstractSuperEntity;

/**
 * Class _SubEntity1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SubEntity1 extends AbstractSuperEntity {

    public static final String SUB_ENTITY_STRING_ATTR_PROPERTY = "subEntityStringAttr";

    public static final String ID_PK_COLUMN = "id";

    public void setSubEntityStringAttr(String subEntityStringAttr) {
        writeProperty("subEntityStringAttr", subEntityStringAttr);
    }
    public String getSubEntityStringAttr() {
        return (String)readProperty("subEntityStringAttr");
    }

}
