package org.apache.cayenne.testdo.relationships_flattened.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.relationships_flattened.FlattenedCircular;

/**
 * Class _FlattenedCircular was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FlattenedCircular extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<FlattenedCircular> SELF = PropertyFactory.createSelf(FlattenedCircular.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "FlattenedCircular", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final ListProperty<FlattenedCircular> SIDE1S = PropertyFactory.createList("side1s", FlattenedCircular.class);
    public static final ListProperty<FlattenedCircular> SIDE2S = PropertyFactory.createList("side2s", FlattenedCircular.class);


    protected Object side1s;
    protected Object side2s;

    public void addToSide1s(FlattenedCircular obj) {
        addToManyTarget("side1s", obj, true);
    }

    public void removeFromSide1s(FlattenedCircular obj) {
        removeToManyTarget("side1s", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<FlattenedCircular> getSide1s() {
        return (List<FlattenedCircular>)readProperty("side1s");
    }

    public void addToSide2s(FlattenedCircular obj) {
        addToManyTarget("side2s", obj, true);
    }

    public void removeFromSide2s(FlattenedCircular obj) {
        removeToManyTarget("side2s", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<FlattenedCircular> getSide2s() {
        return (List<FlattenedCircular>)readProperty("side2s");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "side1s":
                return this.side1s;
            case "side2s":
                return this.side2s;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "side1s":
                this.side1s = val;
                break;
            case "side2s":
                this.side2s = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.side1s);
        out.writeObject(this.side2s);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.side1s = in.readObject();
        this.side2s = in.readObject();
    }

}
