package org.apache.cayenne.testdo.relationships_set_to_many.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.relationships_set_to_many.SetToMany;
import org.apache.cayenne.testdo.relationships_set_to_many.SetToManyTarget;

/**
 * Class _SetToManyTarget was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SetToManyTarget extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<SetToManyTarget> SELF = PropertyFactory.createSelf(SetToManyTarget.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "SetToManyTarget", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final EntityProperty<SetToMany> SET_TO_MANY = PropertyFactory.createEntity("setToMany", SetToMany.class);


    protected Object setToMany;

    public void setSetToMany(SetToMany setToMany) {
        setToOneTarget("setToMany", setToMany, true);
    }

    public SetToMany getSetToMany() {
        return (SetToMany)readProperty("setToMany");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "setToMany":
                return this.setToMany;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "setToMany":
                this.setToMany = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.setToMany);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.setToMany = in.readObject();
    }

}
