package org.apache.cayenne.testdo.relationships_child_master.auto;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.relationships_child_master.Child;
import org.apache.cayenne.testdo.relationships_child_master.Master;

/**
 * Class _Child was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Child extends PersistentObject {

    public static final SelfProperty<Child> SELF = PropertyFactory.createSelf(Child.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "Child", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final EntityProperty<Master> MASTER = PropertyFactory.createEntity("master", Master.class);


    protected Object master;

    public void setMaster(Master master) {
        setToOneTarget("master", master, true);
    }

    public Master getMaster() {
        return (Master)readProperty("master");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "master":
                return this.master;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "master":
                this.master = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
