// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.

[[selectbyid]]
==== Selecting by ID

`ObjectSelect` can match objects of the root entity by their primary key with `byId(..)` and `byIds(..)`:

[source,java,indent=0]
----
include::{java-examples}/SelectByIdTest.java[tags=byId]
----

Both methods accept an id in any of three forms, and `byIds(..)` may mix them:

* a scalar value, for entities with a single-column primary key;
* a `Map` of DB attribute names to values, which is the form to use for a compound primary key;
* an `ObjectId`.

[source,java,indent=0]
----
include::{java-examples}/SelectByIdTest.java[tags=byIdForms]
----

Being an ordinary qualifier, an id match combines with everything else `ObjectSelect` offers - prefetching,
caching, ordering, pagination and further conditions. Under the hood these are shorthands for the "id" expressions of
the entity `SELF` property. So here is a somewhat more verbose equivalent that is also more flexible (e.g. allowing to
chain id qualifier with "or") :

[source,java,indent=0]
----
include::{java-examples}/SelectByIdTest.java[tags=idExpressions]
----

Yet another way to find a single object by PK per <<persistent-objects-objectcontext,the ObjectContext chapter>> is
`ObjectContext.objectForPK(..)`. It will look in the object cache before running a query.