package org.apache.cayenne.testdo.numeric_types.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigInteger;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.numeric_types.BigIntegerEntity;

/**
 * Class _BigIntegerEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BigIntegerEntity extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<BigIntegerEntity> SELF = PropertyFactory.createSelf(BigIntegerEntity.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "BigIntegerEntity", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final NumericProperty<BigInteger> BIG_INTEGER_FIELD = PropertyFactory.createNumeric("bigIntegerField", BigInteger.class);

    protected BigInteger bigIntegerField;


    public void setBigIntegerField(BigInteger bigIntegerField) {
        beforePropertyWrite("bigIntegerField", this.bigIntegerField, bigIntegerField);
        this.bigIntegerField = bigIntegerField;
    }

    public BigInteger getBigIntegerField() {
        beforePropertyRead("bigIntegerField");
        return this.bigIntegerField;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "bigIntegerField":
                return this.bigIntegerField;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "bigIntegerField":
                this.bigIntegerField = (BigInteger)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.bigIntegerField);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.bigIntegerField = (BigInteger)in.readObject();
    }

}
