package org.apache.cayenne.testdo.numeric_types.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.numeric_types.BigDecimalEntity;

/**
 * Class _BigDecimalEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BigDecimalEntity extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<BigDecimalEntity> SELF = PropertyFactory.createSelf(BigDecimalEntity.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "BigDecimalEntity", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final NumericProperty<BigDecimal> BIG_DECIMAL_DECIMAL = PropertyFactory.createNumeric("bigDecimalDecimal", BigDecimal.class);
    public static final NumericProperty<BigDecimal> BIG_DECIMAL_NUMERIC = PropertyFactory.createNumeric("bigDecimalNumeric", BigDecimal.class);

    protected BigDecimal bigDecimalDecimal;
    protected BigDecimal bigDecimalNumeric;


    public void setBigDecimalDecimal(BigDecimal bigDecimalDecimal) {
        beforePropertyWrite("bigDecimalDecimal", this.bigDecimalDecimal, bigDecimalDecimal);
        this.bigDecimalDecimal = bigDecimalDecimal;
    }

    public BigDecimal getBigDecimalDecimal() {
        beforePropertyRead("bigDecimalDecimal");
        return this.bigDecimalDecimal;
    }

    public void setBigDecimalNumeric(BigDecimal bigDecimalNumeric) {
        beforePropertyWrite("bigDecimalNumeric", this.bigDecimalNumeric, bigDecimalNumeric);
        this.bigDecimalNumeric = bigDecimalNumeric;
    }

    public BigDecimal getBigDecimalNumeric() {
        beforePropertyRead("bigDecimalNumeric");
        return this.bigDecimalNumeric;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "bigDecimalDecimal":
                return this.bigDecimalDecimal;
            case "bigDecimalNumeric":
                return this.bigDecimalNumeric;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "bigDecimalDecimal":
                this.bigDecimalDecimal = (BigDecimal)val;
                break;
            case "bigDecimalNumeric":
                this.bigDecimalNumeric = (BigDecimal)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.bigDecimalDecimal);
        out.writeObject(this.bigDecimalNumeric);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.bigDecimalDecimal = (BigDecimal)in.readObject();
        this.bigDecimalNumeric = (BigDecimal)in.readObject();
    }

}
