package org.apache.cayenne.testdo.numeric_types.auto;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.testdo.numeric_types.DecimalPKTest1;

/**
 * Class _DecimalPKTest1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DecimalPKTest1 extends PersistentObject {

    public static final SelfProperty<DecimalPKTest1> SELF = PropertyFactory.createSelf(DecimalPKTest1.class);

    public static final String DECIMAL_PK_PK_COLUMN = "DECIMAL_PK";

    public static final NumericProperty<Double> DECIMAL_PK = PropertyFactory.createNumeric("decimalPK", Double.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);

    protected Double decimalPK;
    protected String name;


    public void setDecimalPK(Double decimalPK) {
        beforePropertyWrite("decimalPK", this.decimalPK, decimalPK);
        this.decimalPK = decimalPK;
    }

    public Double getDecimalPK() {
        beforePropertyRead("decimalPK");
        return this.decimalPK;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "decimalPK":
                return this.decimalPK;
            case "name":
                return this.name;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "decimalPK":
                this.decimalPK = (Double)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
