package org.apache.cayenne.testdo.numeric_types.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.numeric_types.SmallintTestEntity;

/**
 * Class _SmallintTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SmallintTestEntity extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<SmallintTestEntity> SELF = PropertyFactory.createSelf(SmallintTestEntity.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "SmallintTestEntity", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final NumericProperty<Short> SMALLINT_COL = PropertyFactory.createNumeric("smallintCol", Short.class);

    protected Short smallintCol;


    public void setSmallintCol(Short smallintCol) {
        beforePropertyWrite("smallintCol", this.smallintCol, smallintCol);
        this.smallintCol = smallintCol;
    }

    public Short getSmallintCol() {
        beforePropertyRead("smallintCol");
        return this.smallintCol;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "smallintCol":
                return this.smallintCol;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "smallintCol":
                this.smallintCol = (Short)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.smallintCol);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.smallintCol = (Short)in.readObject();
    }

}
