// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.

include::../var.adoc[]

[[runModeler]]
=== Running CayenneModeler

CayenneModeler GUI tool is intended to work with object relational mapping projects. While you can edit your XML by
hand, it is rarely needed, as the Modeler is a pretty advanced tool included in Cayenne distribution. To obtain
CayenneModeler, download Cayenne distribution archive from https://cayenne.apache.org/download.html matching the OS you
are using. Of course Java needs to be installed on the machine where you are going to run the Modeler.

- OS X distribution contains CayenneModeler.app at the root of the distribution disk image.
- Windows distribution contains CayenneModeler.exe file in the bin directory.
- Cross-platform distribution (targeting Linux, but as the name implies, compatible with any OS) contains a runnable
CayenneModeler.jar in the bin directory. It can be executed either by double-clicking, or if the environment is not
configured to execute jars, by running from command-line:

[source]
----
$ java -jar CayenneModeler.jar
----

A path to an existing Cayenne project file can be passed as the only argument to open the project on startup:

[source]
----
$ java -jar CayenneModeler.jar path/to/cayenne-project.xml
----

On macOS the same applies to the `.app` bundle:

[source]
----
$ open CayenneModeler.app --args path/to/cayenne-project.xml
----

==== Running from Maven

The Modeler can also be started from Maven. While it may look like an exotic way to start a GUI application, it has
its benefits - no need to download Cayenne distribution, and the version of the Modeler always matches the version of
the framework. Add the `cayenne-modeler` dependency and an `exec-maven-plugin` execution to the project POM:

[source,xml,subs="verbatim,attributes"]
----
<dependencies>
    <dependency>
        <groupId>org.apache.cayenne.modeler</groupId>
        <artifactId>cayenne-modeler</artifactId>
        <version>{version}</version>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.5.0</version>
            <executions>
                <execution>
                    <id>run-modeler</id>
                    <goals>
                        <goal>java</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <mainClass>org.apache.cayenne.modeler.Main</mainClass>
            </configuration>
        </plugin>
    </plugins>
</build>
----

Then run:

[source]
----
$ mvn exec:java@run-modeler
----