/*****************************************************************
 *   Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 ****************************************************************/
package org.apache.cayenne.unit.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * Minimal JDBC {@link Statement} stub for tests. Implements close/isClosed semantics
 * and exposes the originating {@link Connection}.
 */
public class TestStatement implements Statement {

    private final Connection connection;
    private boolean closed;

    public TestStatement() {
        this(null);
    }

    public TestStatement(Connection connection) {
        this.connection = connection;
    }

    @Override
    public Connection getConnection() {
        return connection;
    }

    @Override
    public void close() {
        closed = true;
    }

    @Override
    public boolean isClosed() {
        return closed;
    }

    // --- everything below is unused by tests ---

    static UnsupportedOperationException uoe() {
        return new UnsupportedOperationException("not implemented in TestStatement");
    }

    @Override public ResultSet executeQuery(String sql) { throw uoe(); }
    @Override public int executeUpdate(String sql) { throw uoe(); }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) { throw uoe(); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) { throw uoe(); }
    @Override public int executeUpdate(String sql, String[] columnNames) { throw uoe(); }
    @Override public boolean execute(String sql) { throw uoe(); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) { throw uoe(); }
    @Override public boolean execute(String sql, int[] columnIndexes) { throw uoe(); }
    @Override public boolean execute(String sql, String[] columnNames) { throw uoe(); }
    @Override public int getMaxFieldSize() { return 0; }
    @Override public void setMaxFieldSize(int max) {}
    @Override public int getMaxRows() { return 0; }
    @Override public void setMaxRows(int max) {}
    @Override public void setEscapeProcessing(boolean enable) {}
    @Override public int getQueryTimeout() { return 0; }
    @Override public void setQueryTimeout(int seconds) {}
    @Override public void cancel() {}
    @Override public SQLWarning getWarnings() { return null; }
    @Override public void clearWarnings() {}
    @Override public void setCursorName(String name) {}
    @Override public ResultSet getResultSet() { return null; }
    @Override public int getUpdateCount() { return -1; }
    @Override public boolean getMoreResults() { return false; }
    @Override public boolean getMoreResults(int current) { return false; }
    @Override public void setFetchDirection(int direction) {}
    @Override public int getFetchDirection() { return ResultSet.FETCH_FORWARD; }
    @Override public void setFetchSize(int rows) {}
    @Override public int getFetchSize() { return 0; }
    @Override public int getResultSetConcurrency() { return ResultSet.CONCUR_READ_ONLY; }
    @Override public int getResultSetType() { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override public int getResultSetHoldability() { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }
    @Override public void addBatch(String sql) {}
    @Override public void clearBatch() {}
    @Override public int[] executeBatch() { return new int[0]; }
    @Override public ResultSet getGeneratedKeys() { throw uoe(); }
    @Override public void setPoolable(boolean poolable) {}
    @Override public boolean isPoolable() { return false; }
    @Override public void closeOnCompletion() {}
    @Override public boolean isCloseOnCompletion() { return false; }
    @Override public <T> T unwrap(Class<T> iface) { throw uoe(); }
    @Override public boolean isWrapperFor(Class<?> iface) { return false; }
}
