package org.apache.cayenne.testdo.deleterules.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.testdo.deleterules.DeleteCascade;
import org.apache.cayenne.testdo.deleterules.DeleteDeny;
import org.apache.cayenne.testdo.deleterules.DeleteNullify;

import java.util.List;

/**
 * Class _DeleteRule was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DeleteRule extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String FROM_CASCADE_PROPERTY = "fromCascade";
    public static final String FROM_DENY_PROPERTY = "fromDeny";
    public static final String FROM_NULLIFY_PROPERTY = "fromNullify";

    public static final String DELETE_RULE_ID_PK_COLUMN = "DELETE_RULE_ID";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToFromCascade(DeleteCascade obj) {
        addToManyTarget(FROM_CASCADE_PROPERTY, obj, true);
    }
    public void removeFromFromCascade(DeleteCascade obj) {
        removeToManyTarget(FROM_CASCADE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DeleteCascade> getFromCascade() {
        return (List<DeleteCascade>)readProperty(FROM_CASCADE_PROPERTY);
    }


    public void addToFromDeny(DeleteDeny obj) {
        addToManyTarget(FROM_DENY_PROPERTY, obj, true);
    }
    public void removeFromFromDeny(DeleteDeny obj) {
        removeToManyTarget(FROM_DENY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DeleteDeny> getFromDeny() {
        return (List<DeleteDeny>)readProperty(FROM_DENY_PROPERTY);
    }


    public void addToFromNullify(DeleteNullify obj) {
        addToManyTarget(FROM_NULLIFY_PROPERTY, obj, true);
    }
    public void removeFromFromNullify(DeleteNullify obj) {
        removeToManyTarget(FROM_NULLIFY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DeleteNullify> getFromNullify() {
        return (List<DeleteNullify>)readProperty(FROM_NULLIFY_PROPERTY);
    }


}
