package org.apache.cayenne.testdo.lob.auto;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.lob.BlobTestEntity;

/**
 * Class _BlobTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BlobTestEntity extends PersistentObject {

    public static final SelfProperty<BlobTestEntity> SELF = PropertyFactory.createSelf(BlobTestEntity.class);

    public static final NumericIdProperty<Integer> BLOB_TEST_ID_PK_PROPERTY = PropertyFactory.createNumericId("BLOB_TEST_ID", "BlobTestEntity", Integer.class);
    public static final String BLOB_TEST_ID_PK_COLUMN = "BLOB_TEST_ID";

    public static final BaseProperty<byte[]> BLOB_COL = PropertyFactory.createBase("blobCol", byte[].class);

    protected byte[] blobCol;


    public void setBlobCol(byte[] blobCol) {
        beforePropertyWrite("blobCol", this.blobCol, blobCol);
        this.blobCol = blobCol;
    }

    public byte[] getBlobCol() {
        beforePropertyRead("blobCol");
        return this.blobCol;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "blobCol":
                return this.blobCol;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "blobCol":
                this.blobCol = (byte[])val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
