package org.apache.cayenne.testdo.lob.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.testdo.lob.NClobTestEntity;

/**
 * Class _NClobTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NClobTestEntity extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<NClobTestEntity> SELF = PropertyFactory.createSelf(NClobTestEntity.class);

    public static final NumericIdProperty<Integer> NCLOB_TEST_ID_PK_PROPERTY = PropertyFactory.createNumericId("NCLOB_TEST_ID", "NClobTestEntity", Integer.class);
    public static final String NCLOB_TEST_ID_PK_COLUMN = "NCLOB_TEST_ID";

    public static final StringProperty<String> NCLOB_COL = PropertyFactory.createString("nclobCol", String.class);

    protected String nclobCol;


    public void setNclobCol(String nclobCol) {
        beforePropertyWrite("nclobCol", this.nclobCol, nclobCol);
        this.nclobCol = nclobCol;
    }

    public String getNclobCol() {
        beforePropertyRead("nclobCol");
        return this.nclobCol;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "nclobCol":
                return this.nclobCol;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "nclobCol":
                this.nclobCol = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.nclobCol);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.nclobCol = (String)in.readObject();
    }

}
