package org.apache.cayenne.testdo.compound.auto;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.testdo.compound.CompoundFkTestEntity;
import org.apache.cayenne.testdo.compound.CompoundPkTestEntity;

/**
 * Class _CompoundFkTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CompoundFkTestEntity extends PersistentObject {

    public static final SelfProperty<CompoundFkTestEntity> SELF = PropertyFactory.createSelf(CompoundFkTestEntity.class);

    public static final NumericIdProperty<Integer> PKEY_PK_PROPERTY = PropertyFactory.createNumericId("PKEY", "CompoundFkTestEntity", Integer.class);
    public static final String PKEY_PK_COLUMN = "PKEY";

    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final EntityProperty<CompoundPkTestEntity> TO_COMPOUND_PK = PropertyFactory.createEntity("toCompoundPk", CompoundPkTestEntity.class);

    protected String name;

    protected Object toCompoundPk;

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setToCompoundPk(CompoundPkTestEntity toCompoundPk) {
        setToOneTarget("toCompoundPk", toCompoundPk, true);
    }

    public CompoundPkTestEntity getToCompoundPk() {
        return (CompoundPkTestEntity)readProperty("toCompoundPk");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "name":
                return this.name;
            case "toCompoundPk":
                return this.toCompoundPk;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "name":
                this.name = (String)val;
                break;
            case "toCompoundPk":
                this.toCompoundPk = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
