package org.apache.cayenne.commitlog.db.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.commitlog.db.Auditable1;
import org.apache.cayenne.commitlog.db.AuditableChild1;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

/**
 * Class _Auditable1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Auditable1 extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Auditable1> SELF = PropertyFactory.createSelf(Auditable1.class);

    public static final String ID_PK_COLUMN = "ID";

    public static final StringProperty<String> CHAR_PROPERTY1 = PropertyFactory.createString("charProperty1", String.class);
    public static final ListProperty<AuditableChild1> CHILDREN1 = PropertyFactory.createList("children1", AuditableChild1.class);

    protected String charProperty1;

    protected Object children1;

    public void setCharProperty1(String charProperty1) {
        beforePropertyWrite("charProperty1", this.charProperty1, charProperty1);
        this.charProperty1 = charProperty1;
    }

    public String getCharProperty1() {
        beforePropertyRead("charProperty1");
        return this.charProperty1;
    }

    public void addToChildren1(AuditableChild1 obj) {
        addToManyTarget("children1", obj, true);
    }

    public void removeFromChildren1(AuditableChild1 obj) {
        removeToManyTarget("children1", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<AuditableChild1> getChildren1() {
        return (List<AuditableChild1>)readProperty("children1");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "charProperty1":
                return this.charProperty1;
            case "children1":
                return this.children1;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "charProperty1":
                this.charProperty1 = (String)val;
                break;
            case "children1":
                this.children1 = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.charProperty1);
        out.writeObject(this.children1);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.charProperty1 = (String)in.readObject();
        this.children1 = in.readObject();
    }

}
