package org.apache.cayenne.testdo.inheritance_vertical.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.testdo.inheritance_vertical.Iv2Root;

/**
 * Class _Iv2Root was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Iv2Root extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Iv2Root> SELF = PropertyFactory.createSelf(Iv2Root.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "Iv2Root", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final StringProperty<String> DISCRIMINATOR = PropertyFactory.createString("discriminator", String.class);

    protected String discriminator;


    public void setDiscriminator(String discriminator) {
        beforePropertyWrite("discriminator", this.discriminator, discriminator);
        this.discriminator = discriminator;
    }

    public String getDiscriminator() {
        beforePropertyRead("discriminator");
        return this.discriminator;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "discriminator":
                return this.discriminator;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "discriminator":
                this.discriminator = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.discriminator);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.discriminator = (String)in.readObject();
    }

}
