package org.apache.cayenne.testdo.inheritance_vertical.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.inheritance_vertical.IvDocument;
import org.apache.cayenne.testdo.inheritance_vertical.IvDocumentA;
import org.apache.cayenne.testdo.inheritance_vertical.IvDocumentB;

/**
 * Class _IvDocumentB was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvDocumentB extends IvDocument {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<IvDocumentB> SELF = PropertyFactory.createSelf(IvDocumentB.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "IvDocumentB", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final EntityProperty<IvDocumentA> RELATED_A = PropertyFactory.createEntity("relatedA", IvDocumentA.class);


    protected Object relatedA;

    public void setOrder(IvDocumentA relatedA) {
        setToOneTarget("relatedA", relatedA, true);
    }

    public IvDocumentA getRelatedA() {
        return (IvDocumentA)readProperty("relatedA");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "relatedA":
                return this.relatedA;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "relatedA":
                this.relatedA = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.relatedA);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.relatedA = in.readObject();
    }

}
