package org.apache.cayenne.testdo.mt.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.mt.MtTable4;
import org.apache.cayenne.testdo.mt.MtTable5;

/**
 * Class _MtTable4 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MtTable4 extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<MtTable4> SELF = PropertyFactory.createSelf(MtTable4.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "MtTable4", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final ListProperty<MtTable5> TABLE5S = PropertyFactory.createList("table5s", MtTable5.class);


    protected Object table5s;

    public void addToTable5s(MtTable5 obj) {
        addToManyTarget("table5s", obj, true);
    }

    public void removeFromTable5s(MtTable5 obj) {
        removeToManyTarget("table5s", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<MtTable5> getTable5s() {
        return (List<MtTable5>)readProperty("table5s");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "table5s":
                return this.table5s;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "table5s":
                this.table5s = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.table5s);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.table5s = in.readObject();
    }

}
