package org.apache.cayenne.testdo.mt.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.mt.MtTable4;
import org.apache.cayenne.testdo.mt.MtTable5;

/**
 * Class _MtTable5 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MtTable5 extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<MtTable5> SELF = PropertyFactory.createSelf(MtTable5.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "MtTable5", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final ListProperty<MtTable4> TABLE4S = PropertyFactory.createList("table4s", MtTable4.class);


    protected Object table4s;

    public void addToTable4s(MtTable4 obj) {
        addToManyTarget("table4s", obj, true);
    }

    public void removeFromTable4s(MtTable4 obj) {
        removeToManyTarget("table4s", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<MtTable4> getTable4s() {
        return (List<MtTable4>)readProperty("table4s");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "table4s":
                return this.table4s;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "table4s":
                this.table4s = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.table4s);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.table4s = in.readObject();
    }

}
