package org.apache.cayenne.testdo.relationship.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.testdo.relationship.CollectionToMany;

/**
 * Class _CollectionToManyTarget was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CollectionToManyTarget extends CayenneDataObject {

    public static final String COLLECTION_TO_MANY_PROPERTY = "collectionToMany";

    public static final String ID_PK_COLUMN = "ID";

    public void setCollectionToMany(CollectionToMany collectionToMany) {
        setToOneTarget(COLLECTION_TO_MANY_PROPERTY, collectionToMany, true);
    }

    public CollectionToMany getCollectionToMany() {
        return (CollectionToMany)readProperty(COLLECTION_TO_MANY_PROPERTY);
    }


}
