package org.apache.cayenne.testdo.relationships_to_many_fk.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.relationships_to_many_fk.ToManyFkRoot;
import org.apache.cayenne.testdo.relationships_to_many_fk.ToManyRoot2;

/**
 * Class _ToManyFkDep was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ToManyFkDep extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String DEP_ID_PK_COLUMN = "DEP_ID";
    public static final String OTHER_ID_PK_COLUMN = "OTHER_ID";

    public static final Property<Integer> DEP_ID = Property.create("depId", Integer.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<ToManyFkRoot> ROOT = Property.create("root", ToManyFkRoot.class);
    public static final Property<ToManyRoot2> ROOT2 = Property.create("root2", ToManyRoot2.class);

    public void setDepId(Integer depId) {
        writeProperty("depId", depId);
    }
    public Integer getDepId() {
        return (Integer)readProperty("depId");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setRoot(ToManyFkRoot root) {
        setToOneTarget("root", root, true);
    }

    public ToManyFkRoot getRoot() {
        return (ToManyFkRoot)readProperty("root");
    }


    public void setRoot2(ToManyRoot2 root2) {
        setToOneTarget("root2", root2, true);
    }

    public ToManyRoot2 getRoot2() {
        return (ToManyRoot2)readProperty("root2");
    }


}
