package org.apache.cayenne.testdo.relationship.auto;

/** Class _ToOneFK1 was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _ToOneFK1 extends org.apache.cayenne.CayenneDataObject {

    public static final String TO_PK_PROPERTY = "toPK";

    public static final String TO_ONEFK1_PK_PK_COLUMN = "TO_ONEFK1_PK";

    public void setToPK(org.apache.cayenne.testdo.relationship.ToOneFK2 toPK) {
        setToOneTarget("toPK", toPK, true);
    }

    public org.apache.cayenne.testdo.relationship.ToOneFK2 getToPK() {
        return (org.apache.cayenne.testdo.relationship.ToOneFK2)readProperty("toPK");
    } 
    
    
}
