package org.apache.cayenne.testdo.relationships_to_one_fk.auto;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.relationships_to_one_fk.ToOneFK1;
import org.apache.cayenne.testdo.relationships_to_one_fk.ToOneFK2;

/**
 * Class _ToOneFK1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ToOneFK1 extends PersistentObject {

    public static final SelfProperty<ToOneFK1> SELF = PropertyFactory.createSelf(ToOneFK1.class);

    public static final NumericIdProperty<Integer> TO_ONE_FK1_PK_PK_PROPERTY = PropertyFactory.createNumericId("TO_ONE_FK1_PK", "ToOneFK1", Integer.class);
    public static final String TO_ONE_FK1_PK_PK_COLUMN = "TO_ONE_FK1_PK";

    public static final EntityProperty<ToOneFK2> TO_PK = PropertyFactory.createEntity("toPK", ToOneFK2.class);


    protected Object toPK;

    public void setToPK(ToOneFK2 toPK) {
        setToOneTarget("toPK", toPK, true);
    }

    public ToOneFK2 getToPK() {
        return (ToOneFK2)readProperty("toPK");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "toPK":
                return this.toPK;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "toPK":
                this.toPK = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
