package org.apache.cayenne.testdo.qualified.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.testdo.qualified.Qualified1;
import org.apache.cayenne.testdo.qualified.Qualified2;

/**
 * Class _Qualified1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Qualified1 extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Qualified1> SELF = PropertyFactory.createSelf(Qualified1.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("ID", "Qualified1", Integer.class);
    public static final String ID_PK_COLUMN = "ID";

    public static final BaseProperty<Boolean> DELETED = PropertyFactory.createBase("deleted", Boolean.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final ListProperty<Qualified2> QUALIFIED2S = PropertyFactory.createList("qualified2s", Qualified2.class);

    protected Boolean deleted;
    protected String name;

    protected Object qualified2s;

    public void setDeleted(Boolean deleted) {
        beforePropertyWrite("deleted", this.deleted, deleted);
        this.deleted = deleted;
    }

    public Boolean getDeleted() {
        beforePropertyRead("deleted");
        return this.deleted;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void addToQualified2s(Qualified2 obj) {
        addToManyTarget("qualified2s", obj, true);
    }

    public void removeFromQualified2s(Qualified2 obj) {
        removeToManyTarget("qualified2s", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Qualified2> getQualified2s() {
        return (List<Qualified2>)readProperty("qualified2s");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "deleted":
                return this.deleted;
            case "name":
                return this.name;
            case "qualified2s":
                return this.qualified2s;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "deleted":
                this.deleted = (Boolean)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "qualified2s":
                this.qualified2s = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.deleted);
        out.writeObject(this.name);
        out.writeObject(this.qualified2s);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.deleted = (Boolean)in.readObject();
        this.name = (String)in.readObject();
        this.qualified2s = in.readObject();
    }

}
