package org.apache.cayenne.testdo.unsupported_distinct_types.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.unsupported_distinct_types.Customer;
import org.apache.cayenne.testdo.unsupported_distinct_types.Product;

/**
 * Class _Product was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Product extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> LONGVARCHAR_COL = Property.create("longvarcharCol", String.class);
    public static final Property<List<Product>> BASE = Property.create("base", List.class);
    public static final Property<List<Product>> CONTAINED = Property.create("contained", List.class);
    public static final Property<List<Customer>> ORDER_BY = Property.create("orderBy", List.class);

    public void setLongvarcharCol(String longvarcharCol) {
        writeProperty("longvarcharCol", longvarcharCol);
    }
    public String getLongvarcharCol() {
        return (String)readProperty("longvarcharCol");
    }

    public void addToBase(Product obj) {
        addToManyTarget("base", obj, true);
    }
    public void removeFromBase(Product obj) {
        removeToManyTarget("base", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Product> getBase() {
        return (List<Product>)readProperty("base");
    }


    public void addToContained(Product obj) {
        addToManyTarget("contained", obj, true);
    }
    public void removeFromContained(Product obj) {
        removeToManyTarget("contained", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Product> getContained() {
        return (List<Product>)readProperty("contained");
    }


    public void addToOrderBy(Customer obj) {
        addToManyTarget("orderBy", obj, true);
    }
    public void removeFromOrderBy(Customer obj) {
        removeToManyTarget("orderBy", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Customer> getOrderBy() {
        return (List<Customer>)readProperty("orderBy");
    }


}
