// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.

== Starting Cayenne

=== Starting and Stopping CayenneRuntime

In runtime Cayenne is accessed via `org.apache.cayenne.runtime.CayenneRuntime`. CayenneRuntime is created by calling a convenient builder:

[source,java,indent=0]
----
include::{java-examples}/StartingTest.java[tags=start]
----

The parameter you pass to the builder is a location of the main project file. Location is a '/'-separated path (same path separator is used on UNIX and Windows) that is resolved relative to the application classpath. The project file can be placed in the root package or in a subpackage (e.g. in the code above it is in "com/example" subpackage).

CayenneRuntime encapsulates a single Cayenne stack. Most applications will just have one CayenneRuntime using it to create as many ObjectContexts as needed, access the Dependency Injection (DI) container and work with other Cayenne features. Internally CayenneRuntime is just a thin wrapper around the DI container. Detailed features of the container are discussed in <<Customizing Cayenne Runtime>> chapter. Here we'll just show an example of how an application might turn on external transactions:

[source,java,indent=0]
----
include::{java-examples}/StartingTest.java[tags=externalTransactions]
----

It is a good idea to shut down the runtime when it is no longer needed, usually before the application itself is shutdown:

[source,java,indent=0]
----
include::{java-examples}/StartingTest.java[tags=stop]
----

When a runtime object has the same scope as the application, this may not be always necessary, however in some cases it is essential, and is generally considered a good practice. E.g. in a web container hot redeploy of a webapp will cause resource leaks and eventual OutOfMemoryError if the application fails to shutdown CayenneRuntime.

=== Connecting to a Database

The mapping project does not contain any database connection information. The database is defined in the code, when
the runtime is created, as a DataNode. In the simplest case a DataNode is created from a `DataSource`. It can be any
`DataSource`, e.g., the one provided by your application container, or the one built with `CayenneDataSource`:

[source,java,indent=0]
----
include::{java-examples}/StartingTest.java[tags=dataSource]
----

When a DataNode needs to be customized, e.g., to let Cayenne create the DB schema on the first connection, to set
a specific DbAdapter, or to give the node a name, use a `DataNodeDescriptor`:

[source,java,indent=0]
----
include::{java-examples}/StartingTest.java[tags=dataNodeDescriptor]
----

There can be more than one DataNode. Each one is linked to its DataMaps by name. The "default" DataNode is optional,
and is used for all the DataMaps that are not linked to a node explicitly:

[source,java,indent=0]
----
include::{java-examples}/StartingTest.java[tags=multipleDataNodes]
----

=== Merging Multiple Projects

CayenneRuntime requires at least one mapping project to run. But it can also take multiple projects and merge them together in a single configuration. This way different parts of a database can be mapped independently from each other (even by different software providers), and combined in runtime when assembling an application. Doing it is as easy as passing multiple project locations to CayenneRuntime builder:

[source,java,indent=0]
----
include::{java-examples}/StartingTest.java[tags=multipleProjects]
----

When the projects are merged, the following rules are applied:

- The order of projects matters during merge. If there are two conflicting metadata objects belonging to two projects, an object from the last project takes precedence over the object from the first one. This makes possible to override pieces of metadata. This is also similar to how DI modules are merged in Cayenne.

- Runtime DataDomain name is set to the name of the last project in the list.

- Runtime DataDomain properties are the same as the properties of the last project in the list. I.e. properties are not merged to avoid invalid combinations and unexpected runtime behavior.

- If there are two or more DataMaps with the same name, only one DataMap is used in the merged project, the rest are discarded. Same precedence rules apply - DataMap from the project with the highest index in the project list overrides all other DataMaps with the same name.

- DataNodes are not a part of the projects. After the merge the DataMaps are linked to the DataNodes as described above. If any DataMaps are not explicitly linked to DataNodes, their queries will be executed via the default DataNode. This makes it possible to build mapping "libraries" that are only associated with a specific database in runtime.
