/* Generated By:JJTree: Do not edit this line. src/cayenne/java/org/objectstyle/cayenne/exp/parser/ExpressionParserTreeConstants.java */

package org.objectstyle.cayenne.exp.parser;

public interface ExpressionParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTOR = 1;
  public int JJTAND = 2;
  public int JJTNOT = 3;
  public int JJTEQUAL = 4;
  public int JJTNOTEQUAL = 5;
  public int JJTLESSOREQUAL = 6;
  public int JJTLESS = 7;
  public int JJTGREATER = 8;
  public int JJTGREATEROREQUAL = 9;
  public int JJTLIKE = 10;
  public int JJTLIKEIGNORECASE = 11;
  public int JJTIN = 12;
  public int JJTBETWEEN = 13;
  public int JJTNOTLIKE = 14;
  public int JJTNOTLIKEIGNORECASE = 15;
  public int JJTNOTIN = 16;
  public int JJTNOTBETWEEN = 17;
  public int JJTLIST = 18;
  public int JJTSCALAR = 19;
  public int JJTADD = 20;
  public int JJTSUBTRACT = 21;
  public int JJTMULTIPLY = 22;
  public int JJTDIVIDE = 23;
  public int JJTNEGATE = 24;
  public int JJTNAMEDPARAMETER = 25;
  public int JJTOBJPATH = 26;
  public int JJTDBPATH = 27;


  public String[] jjtNodeName = {
    "void",
    "Or",
    "And",
    "Not",
    "Equal",
    "NotEqual",
    "LessOrEqual",
    "Less",
    "Greater",
    "GreaterOrEqual",
    "Like",
    "LikeIgnoreCase",
    "In",
    "Between",
    "NotLike",
    "NotLikeIgnoreCase",
    "NotIn",
    "NotBetween",
    "List",
    "Scalar",
    "Add",
    "Subtract",
    "Multiply",
    "Divide",
    "Negate",
    "NamedParameter",
    "ObjPath",
    "DbPath",
  };
}
