package org.apache.cayenne.testdo.cay_2666.auto;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.testdo.cay_2666.CAY2666;

/**
 * Class _CAY2666 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CAY2666 extends PersistentObject {

    public static final SelfProperty<CAY2666> SELF = PropertyFactory.createSelf(CAY2666.class);

    public static final String ID_PK_COLUMN = "ID";

    public static final StringProperty<String> NAME$ = PropertyFactory.createString("name$", String.class);

    protected String name$;


    public void setName$(String name$) {
        beforePropertyWrite("name$", this.name$, name$);
        this.name$ = name$;
    }

    public String getName$() {
        beforePropertyRead("name$");
        return this.name$;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "name$":
                return this.name$;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "name$":
                this.name$ = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
