<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~    https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>cayenne-docs-parent</artifactId>
        <groupId>org.apache.cayenne.docs</groupId>
        <version>5.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>cayenne-guide</artifactId>

    <packaging>jar</packaging>
    <name>cayenne-guide: AsciiDoc - Cayenne Framework Guide</name>

    <dependencies>

        <!-- Test dependencies. Java code examples in the docs are included from the compiled tests -->
        <dependency>
            <groupId>org.apache.cayenne</groupId>
            <artifactId>cayenne-cache-invalidation</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.cayenne</groupId>
            <artifactId>cayenne-crypto</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.cayenne</groupId>
            <artifactId>cayenne-jcache</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- The tests are the source of the code examples in the docs. Do not allow deprecated API there -->
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-testCompile</id>
                        <configuration>
                            <showWarnings>true</showWarnings>
                            <compilerArgs>
                                <arg>-Xlint:deprecation,removal</arg>
                                <arg>-Werror</arg>
                            </compilerArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>io.bootique.tools</groupId>
                        <artifactId>hugo-asciidoctorj-extension</artifactId>
                        <version>${hugo.asciidoctorj.extension.version}</version>
                    </dependency>
                </dependencies>

                <executions>
                    <!-- generate "embeddable" html content with front matter and without header/footer/styles -->
                    <execution>
                        <id>asciidoctor-html-web</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                        <configuration>
                            <backend>html5</backend>
                            <standalone>false</standalone> <!-- do not generate header and footer -->
                            <outputDirectory>${project.build.directory}/tmp/</outputDirectory>
                            <extensions>
                                <extension>
                                    <className>io.bootique.tools.asciidoctorj.HugoExtension</className>
                                </extension>
                            </extensions>
                            <attributes>
                                <toc>auto</toc>
                            </attributes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>assembly</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctor-maven-plugin</artifactId>
                        <executions>
                            <!-- generate standalone html help -->
                            <execution>
                                <id>asciidoctor-html-standalone</id>
                                <phase>${build.docs}</phase>
                                <goals>
                                    <goal>process-asciidoc</goal>
                                </goals>
                                <configuration>
                                    <backend>html5</backend>
                                    <embedAssets>true</embedAssets>
                                    <attributes>
                                        <toc>left</toc>
                                        <source-highlighter>coderay</source-highlighter>
                                    </attributes>
                                </configuration>
                            </execution>

                            <!-- generate PDF -->
                            <execution>
                                <id>generate-pdf-doc</id>
                                <phase>${build.docs}</phase>
                                <goals>
                                    <goal>process-asciidoc</goal>
                                </goals>
                                <configuration>
                                    <backend>pdf</backend>
                                    <attributes>
                                        <pagenums />
                                        <toc />
                                        <source-highlighter>coderay</source-highlighter>
                                    </attributes>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>