package org.apache.cayenne.testdo.relationships_delete_rules.auto;

import java.util.List;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.testdo.relationships_delete_rules.DeleteRuleFlatA;
import org.apache.cayenne.testdo.relationships_delete_rules.DeleteRuleFlatB;

/**
 * Class _DeleteRuleFlatA was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DeleteRuleFlatA extends PersistentObject {

    public static final SelfProperty<DeleteRuleFlatA> SELF = PropertyFactory.createSelf(DeleteRuleFlatA.class);

    public static final NumericIdProperty<Integer> FLATA_ID_PK_PROPERTY = PropertyFactory.createNumericId("FLATA_ID", "DeleteRuleFlatA", Integer.class);
    public static final String FLATA_ID_PK_COLUMN = "FLATA_ID";

    public static final ListProperty<DeleteRuleFlatB> FLAT_B = PropertyFactory.createList("flatB", DeleteRuleFlatB.class);


    protected Object flatB;

    public void addToFlatB(DeleteRuleFlatB obj) {
        addToManyTarget("flatB", obj, true);
    }

    public void removeFromFlatB(DeleteRuleFlatB obj) {
        removeToManyTarget("flatB", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<DeleteRuleFlatB> getFlatB() {
        return (List<DeleteRuleFlatB>)readProperty("flatB");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "flatB":
                return this.flatB;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "flatB":
                this.flatB = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

}
