package org.apache.cayenne.testdo.relationships_qualifier.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.relationships_qualifier.Course;
import org.apache.cayenne.testdo.relationships_qualifier.Rule;
import org.apache.cayenne.testdo.relationships_qualifier.RuleRelation;

/**
 * Class _CourseRuleRelation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CourseRuleRelation extends RuleRelation {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String COURSES_PROPERTY = "courses";
    @Deprecated
    public static final String RULE_PROPERTY = "rule";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Course> COURSES = new Property<Course>("courses");
    public static final Property<Rule> RULE = new Property<Rule>("rule");

    public void setCourses(Course courses) {
        setToOneTarget("courses", courses, true);
    }

    public Course getCourses() {
        return (Course)readProperty("courses");
    }


    public void setRule(Rule rule) {
        setToOneTarget("rule", rule, true);
    }

    public Rule getRule() {
        return (Rule)readProperty("rule");
    }


}
