package org.apache.cayenne.testdo.relationships_qualifier.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.relationships_qualifier.CourseRuleRelation;

/**
 * Class _Course was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Course extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String ID_PROPERTY = "id";
    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String RELATIONS_PROPERTY = "relations";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Integer> ID = new Property<Integer>("id");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<CourseRuleRelation>> RELATIONS = new Property<List<CourseRuleRelation>>("relations");

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToRelations(CourseRuleRelation obj) {
        addToManyTarget("relations", obj, true);
    }
    public void removeFromRelations(CourseRuleRelation obj) {
        removeToManyTarget("relations", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CourseRuleRelation> getRelations() {
        return (List<CourseRuleRelation>)readProperty("relations");
    }


}
