package org.apache.cayenne.testdo.relationships_qualifier.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.relationships_qualifier.RuleRelation;
import org.apache.cayenne.testdo.relationships_qualifier.RuleStatus;

/**
 * Class _Rule was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Rule extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String STATUS_ID_PROPERTY = "statusId";
    @Deprecated
    public static final String RELATION_PROPERTY = "relation";
    @Deprecated
    public static final String RULE_STATUS_PROPERTY = "ruleStatus";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<Integer> STATUS_ID = new Property<Integer>("statusId");
    public static final Property<List<RuleRelation>> RELATION = new Property<List<RuleRelation>>("relation");
    public static final Property<RuleStatus> RULE_STATUS = new Property<RuleStatus>("ruleStatus");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setStatusId(Integer statusId) {
        writeProperty("statusId", statusId);
    }
    public Integer getStatusId() {
        return (Integer)readProperty("statusId");
    }

    public void addToRelation(RuleRelation obj) {
        addToManyTarget("relation", obj, true);
    }
    public void removeFromRelation(RuleRelation obj) {
        removeToManyTarget("relation", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RuleRelation> getRelation() {
        return (List<RuleRelation>)readProperty("relation");
    }


    public void setRuleStatus(RuleStatus ruleStatus) {
        setToOneTarget("ruleStatus", ruleStatus, true);
    }

    public RuleStatus getRuleStatus() {
        return (RuleStatus)readProperty("ruleStatus");
    }


}
