// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.
=== Getting started with persistent objects
In this chapter we'll learn about persistent objects, how to customize them and how to
create and save them in DB.

==== Inspecting and Customizing Persistent Objects
Persistent classes in Cayenne implement a `Persistent` interface. If you inspect any of
the classes generated earlier in this tutorial (e.g.
`org.example.cayenne.persistent.Artist`), you'll see that it extends a class with the name
that starts with underscore (`org.example.cayenne.persistent.auto._Artist`), which in turn
extends from `org.apache.cayenne.PersistentObject`. Splitting each persistent class into
user-customizable subclass (`Xyz`) and a generated superclass (`_Xyz`) is a useful technique
to avoid overwriting the custom code when refreshing classes from the mapping
model.

Let's for instance add a utility method to the Artist class that sets Artist date of
birth, taking a string argument for the date. It will be preserved even if the model
changes later:

[source,java]
----
include::{java-include-dir}/persistent/Artist.java[tag=content]
----

==== Create New Objects
Now we'll create a bunch of objects and save them to the database. An object is
created and registered with `ObjectContext` using "`newObject`" method. Objects *must* be registered
with `DataContext` to be persisted and to allow setting relationships with other objects.
Add this code to the "main" method of the Main class:

[source,java,indent=0]
----
include::{java-include-dir}/Main.java[tag=new-artist]
----

Note that at this point "picasso" object is only stored in memory and is not saved in
the database. Let's continue by adding a Metropolitan Museum "`Gallery`" object and a few
Picasso "Paintings":

[source,java,indent=0]
----
include::{java-include-dir}/Main.java[tag=new-painting]
----

Now we can link the objects together, establishing relationships. Note that in each
case below relationships are automatically established in both directions (e.g.
`picasso.addToPaintings(girl)` has exactly the same effect as
`girl.setToArtist(picasso)`).

[source, java, indent=0]
----
include::{java-include-dir}/Main.java[tag=link-objects]
----

Now lets save all five new objects, in a single method call:

[source, java, indent=0]
----
include::{java-include-dir}/Main.java[tag=commit]
----

Now you can run the application again as described in the previous chapter. The new
output will show a few actual DB operations:

    ...
    INFO: --- transaction started.
    INFO: No schema detected, will create mapped tables
    INFO: CREATE TABLE GALLERY (ID INTEGER NOT NULL, NAME VARCHAR (200), PRIMARY KEY (ID))
    INFO: CREATE TABLE ARTIST (DATE_OF_BIRTH DATE, ID INTEGER NOT NULL, NAME VARCHAR (200), PRIMARY KEY (ID))
    INFO: CREATE TABLE PAINTING (ARTIST_ID INTEGER, GALLERY_ID INTEGER, ID INTEGER NOT NULL,
          NAME VARCHAR (200), PRIMARY KEY (ID))
    INFO: ALTER TABLE PAINTING ADD FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST (ID)
    INFO: ALTER TABLE PAINTING ADD FOREIGN KEY (GALLERY_ID) REFERENCES GALLERY (ID)
    INFO: CREATE TABLE AUTO_PK_SUPPORT (
          TABLE_NAME CHAR(100) NOT NULL,  NEXT_ID BIGINT NOT NULL,  PRIMARY KEY(TABLE_NAME))
    INFO: DELETE FROM AUTO_PK_SUPPORT WHERE TABLE_NAME IN ('ARTIST', 'GALLERY', 'PAINTING')
    INFO: INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('ARTIST', 200)
    INFO: INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('GALLERY', 200)
    INFO: INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('PAINTING', 200)
    INFO: SELECT NEXT_ID FROM AUTO_PK_SUPPORT WHERE TABLE_NAME = ? FOR UPDATE [bind: 1:'ARTIST']
    INFO: SELECT NEXT_ID FROM AUTO_PK_SUPPORT WHERE TABLE_NAME = ? FOR UPDATE [bind: 1:'GALLERY']
    INFO: SELECT NEXT_ID FROM AUTO_PK_SUPPORT WHERE TABLE_NAME = ? FOR UPDATE [bind: 1:'PAINTING']
    INFO: INSERT INTO GALLERY (ID, NAME) VALUES (?, ?)
    INFO: [batch bind: 1->ID:200, 2->NAME:'Metropolitan Museum of Art']
    INFO: === updated 1 row.
    INFO: INSERT INTO ARTIST (DATE_OF_BIRTH, ID, NAME) VALUES (?, ?, ?)
    INFO: [batch bind: 1->DATE_OF_BIRTH:'1881-10-25 00:00:00.0', 2->ID:200, 3->NAME:'Pablo Picasso']
    INFO: === updated 1 row.
    INFO: INSERT INTO PAINTING (ARTIST_ID, GALLERY_ID, ID, NAME) VALUES (?, ?, ?, ?)
    INFO: [batch bind: 1->ARTIST_ID:200, 2->GALLERY_ID:200, 3->ID:200, 4->NAME:'Gertrude Stein']
    INFO: [batch bind: 1->ARTIST_ID:200, 2->GALLERY_ID:200, 3->ID:201, 4->NAME:'Girl Reading at a Table']
    INFO: === updated 2 rows.
    INFO: +++ transaction committed.

So first Cayenne creates the needed tables (remember, we used
"`CreateIfNoSchemaStrategy`"). Then it runs a number of inserts, generating primary keys
on the fly. Not bad for just a few lines of code.
    

