package org.objectstyle.petstore.domain.auto;

import java.util.List;

/** Class _Category was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Category extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String BANNER_PROPERTY = "banner";
    public static final String PRODUCTS_PROPERTY = "products";
    public static final String PROFILES_PROPERTY = "profiles";

    public static final String CATID_PK_COLUMN = "catid";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setBanner(org.objectstyle.petstore.domain.BannerData banner) {
        setToOneTarget("banner", banner, true);
    }

    public org.objectstyle.petstore.domain.BannerData getBanner() {
        return (org.objectstyle.petstore.domain.BannerData)readProperty("banner");
    } 
    
    
    public void addToProducts(org.objectstyle.petstore.domain.Product obj) {
        addToManyTarget("products", obj, true);
    }
    public void removeFromProducts(org.objectstyle.petstore.domain.Product obj) {
        removeToManyTarget("products", obj, true);
    }
    public List getProducts() {
        return (List)readProperty("products");
    }
    
    
    public void addToProfiles(org.objectstyle.petstore.domain.Profile obj) {
        addToManyTarget("profiles", obj, true);
    }
    public void removeFromProfiles(org.objectstyle.petstore.domain.Profile obj) {
        removeToManyTarget("profiles", obj, true);
    }
    public List getProfiles() {
        return (List)readProperty("profiles");
    }
    
    
}
