package org.objectstyle.petstore.domain.auto;

/** Class _LineItem was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _LineItem extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String QUANTITY_PROPERTY = "quantity";
    public static final String UNIT_PRICE_PROPERTY = "unitPrice";
    public static final String ITEM_PROPERTY = "item";
    public static final String ORDER_PROPERTY = "order";
    public static final String STATUS_PROPERTY = "status";

    public static final String LINENUM_PK_COLUMN = "linenum";
    public static final String ORDERID_PK_COLUMN = "orderid";

    public void setQuantity(Integer quantity) {
        writeProperty("quantity", quantity);
    }
    public Integer getQuantity() {
        return (Integer)readProperty("quantity");
    }
    
    
    public void setUnitPrice(java.math.BigDecimal unitPrice) {
        writeProperty("unitPrice", unitPrice);
    }
    public java.math.BigDecimal getUnitPrice() {
        return (java.math.BigDecimal)readProperty("unitPrice");
    }
    
    
    public void setItem(org.objectstyle.petstore.domain.Item item) {
        setToOneTarget("item", item, true);
    }

    public org.objectstyle.petstore.domain.Item getItem() {
        return (org.objectstyle.petstore.domain.Item)readProperty("item");
    } 
    
    
    public void setOrder(org.objectstyle.petstore.domain.Order order) {
        setToOneTarget("order", order, true);
    }

    public org.objectstyle.petstore.domain.Order getOrder() {
        return (org.objectstyle.petstore.domain.Order)readProperty("order");
    } 
    
    
    public void setStatus(org.objectstyle.petstore.domain.OrderStatus status) {
        setToOneTarget("status", status, true);
    }

    public org.objectstyle.petstore.domain.OrderStatus getStatus() {
        return (org.objectstyle.petstore.domain.OrderStatus)readProperty("status");
    } 
    
    
}
