package org.objectstyle.petstore.domain.auto;

import java.util.List;

/** Class _Order was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Order extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String BILL_ADDRESS1_PROPERTY = "billAddress1";
    public static final String BILL_ADDRESS2_PROPERTY = "billAddress2";
    public static final String BILL_CITY_PROPERTY = "billCity";
    public static final String BILL_COUNTRY_PROPERTY = "billCountry";
    public static final String BILL_STATE_PROPERTY = "billState";
    public static final String BILL_TO_FIRST_NAME_PROPERTY = "billToFirstName";
    public static final String BILL_TO_LAST_NAME_PROPERTY = "billToLastName";
    public static final String BILL_ZIP_PROPERTY = "billZip";
    public static final String CARD_TYPE_PROPERTY = "cardType";
    public static final String COURIER_PROPERTY = "courier";
    public static final String CREDIT_CARD_PROPERTY = "creditCard";
    public static final String EXPIRY_DATE_PROPERTY = "expiryDate";
    public static final String LOCALE_PROPERTY = "locale";
    public static final String ORDER_DATE_PROPERTY = "orderDate";
    public static final String SHIP_ADDRESS1_PROPERTY = "shipAddress1";
    public static final String SHIP_ADDRESS2_PROPERTY = "shipAddress2";
    public static final String SHIP_CITY_PROPERTY = "shipCity";
    public static final String SHIP_COUNTRY_PROPERTY = "shipCountry";
    public static final String SHIP_STATE_PROPERTY = "shipState";
    public static final String SHIP_TO_FIRST_NAME_PROPERTY = "shipToFirstName";
    public static final String SHIP_TO_LAST_NAME_PROPERTY = "shipToLastName";
    public static final String SHIP_ZIP_PROPERTY = "shipZip";
    public static final String TOTAL_PRICE_PROPERTY = "totalPrice";
    public static final String ACCOUNT_PROPERTY = "account";
    public static final String LINE_ITEMS_PROPERTY = "lineItems";

    public static final String ORDERID_PK_COLUMN = "orderid";

    public void setBillAddress1(String billAddress1) {
        writeProperty("billAddress1", billAddress1);
    }
    public String getBillAddress1() {
        return (String)readProperty("billAddress1");
    }
    
    
    public void setBillAddress2(String billAddress2) {
        writeProperty("billAddress2", billAddress2);
    }
    public String getBillAddress2() {
        return (String)readProperty("billAddress2");
    }
    
    
    public void setBillCity(String billCity) {
        writeProperty("billCity", billCity);
    }
    public String getBillCity() {
        return (String)readProperty("billCity");
    }
    
    
    public void setBillCountry(String billCountry) {
        writeProperty("billCountry", billCountry);
    }
    public String getBillCountry() {
        return (String)readProperty("billCountry");
    }
    
    
    public void setBillState(String billState) {
        writeProperty("billState", billState);
    }
    public String getBillState() {
        return (String)readProperty("billState");
    }
    
    
    public void setBillToFirstName(String billToFirstName) {
        writeProperty("billToFirstName", billToFirstName);
    }
    public String getBillToFirstName() {
        return (String)readProperty("billToFirstName");
    }
    
    
    public void setBillToLastName(String billToLastName) {
        writeProperty("billToLastName", billToLastName);
    }
    public String getBillToLastName() {
        return (String)readProperty("billToLastName");
    }
    
    
    public void setBillZip(String billZip) {
        writeProperty("billZip", billZip);
    }
    public String getBillZip() {
        return (String)readProperty("billZip");
    }
    
    
    public void setCardType(String cardType) {
        writeProperty("cardType", cardType);
    }
    public String getCardType() {
        return (String)readProperty("cardType");
    }
    
    
    public void setCourier(String courier) {
        writeProperty("courier", courier);
    }
    public String getCourier() {
        return (String)readProperty("courier");
    }
    
    
    public void setCreditCard(String creditCard) {
        writeProperty("creditCard", creditCard);
    }
    public String getCreditCard() {
        return (String)readProperty("creditCard");
    }
    
    
    public void setExpiryDate(String expiryDate) {
        writeProperty("expiryDate", expiryDate);
    }
    public String getExpiryDate() {
        return (String)readProperty("expiryDate");
    }
    
    
    public void setLocale(String locale) {
        writeProperty("locale", locale);
    }
    public String getLocale() {
        return (String)readProperty("locale");
    }
    
    
    public void setOrderDate(java.util.Date orderDate) {
        writeProperty("orderDate", orderDate);
    }
    public java.util.Date getOrderDate() {
        return (java.util.Date)readProperty("orderDate");
    }
    
    
    public void setShipAddress1(String shipAddress1) {
        writeProperty("shipAddress1", shipAddress1);
    }
    public String getShipAddress1() {
        return (String)readProperty("shipAddress1");
    }
    
    
    public void setShipAddress2(String shipAddress2) {
        writeProperty("shipAddress2", shipAddress2);
    }
    public String getShipAddress2() {
        return (String)readProperty("shipAddress2");
    }
    
    
    public void setShipCity(String shipCity) {
        writeProperty("shipCity", shipCity);
    }
    public String getShipCity() {
        return (String)readProperty("shipCity");
    }
    
    
    public void setShipCountry(String shipCountry) {
        writeProperty("shipCountry", shipCountry);
    }
    public String getShipCountry() {
        return (String)readProperty("shipCountry");
    }
    
    
    public void setShipState(String shipState) {
        writeProperty("shipState", shipState);
    }
    public String getShipState() {
        return (String)readProperty("shipState");
    }
    
    
    public void setShipToFirstName(String shipToFirstName) {
        writeProperty("shipToFirstName", shipToFirstName);
    }
    public String getShipToFirstName() {
        return (String)readProperty("shipToFirstName");
    }
    
    
    public void setShipToLastName(String shipToLastName) {
        writeProperty("shipToLastName", shipToLastName);
    }
    public String getShipToLastName() {
        return (String)readProperty("shipToLastName");
    }
    
    
    public void setShipZip(String shipZip) {
        writeProperty("shipZip", shipZip);
    }
    public String getShipZip() {
        return (String)readProperty("shipZip");
    }
    
    
    public void setTotalPrice(java.math.BigDecimal totalPrice) {
        writeProperty("totalPrice", totalPrice);
    }
    public java.math.BigDecimal getTotalPrice() {
        return (java.math.BigDecimal)readProperty("totalPrice");
    }
    
    
    public void setAccount(org.objectstyle.petstore.domain.Account account) {
        setToOneTarget("account", account, true);
    }

    public org.objectstyle.petstore.domain.Account getAccount() {
        return (org.objectstyle.petstore.domain.Account)readProperty("account");
    } 
    
    
    public void addToLineItems(org.objectstyle.petstore.domain.LineItem obj) {
        addToManyTarget("lineItems", obj, true);
    }
    public void removeFromLineItems(org.objectstyle.petstore.domain.LineItem obj) {
        removeToManyTarget("lineItems", obj, true);
    }
    public List getLineItems() {
        return (List)readProperty("lineItems");
    }
    
    
}
