package org.objectstyle.petstore.domain.auto;

/** Class _User was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _User extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String PASSWORD_PROPERTY = "password";
    public static final String ACCOUNT_PROPERTY = "account";

    public static final String USERNAME_PK_COLUMN = "username";

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }
    
    
    public void setAccount(org.objectstyle.petstore.domain.Account account) {
        setToOneTarget("account", account, true);
    }

    public org.objectstyle.petstore.domain.Account getAccount() {
        return (org.objectstyle.petstore.domain.Account)readProperty("account");
    } 
    
    
}
