package org.apache.cayenne.testdo.compound.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.compound.CharFkTestEntity;

/**
 * Class _CharPkTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CharPkTestEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PK_COL_PK_COLUMN = "PK_COL";

    public static final Property<String> OTHER_COL = Property.create("otherCol", String.class);
    public static final Property<String> PK_COL = Property.create("pkCol", String.class);
    public static final Property<List<CharFkTestEntity>> CHAR_FKS = Property.create("charFKs", List.class);

    public void setOtherCol(String otherCol) {
        writeProperty("otherCol", otherCol);
    }
    public String getOtherCol() {
        return (String)readProperty("otherCol");
    }

    public void setPkCol(String pkCol) {
        writeProperty("pkCol", pkCol);
    }
    public String getPkCol() {
        return (String)readProperty("pkCol");
    }

    public void addToCharFKs(CharFkTestEntity obj) {
        addToManyTarget("charFKs", obj, true);
    }
    public void removeFromCharFKs(CharFkTestEntity obj) {
        removeToManyTarget("charFKs", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CharFkTestEntity> getCharFKs() {
        return (List<CharFkTestEntity>)readProperty("charFKs");
    }


}
