CREATE TABLE Parent (
  id INTEGER NOT NULL,
  COL2 CHAR(25),
  COL3 DECIMAL(10,2),
  COL4 VARCHAR(25),
  COL5 DATE,

  PRIMARY KEY (id),
  UNIQUE (COL3)
);

CREATE TABLE Child (
  id INTEGER NOT NULL,
  Parent_id CHAR(25),
  COL3 DECIMAL(10,2),
  COL4 VARCHAR(25),
  COL5 DATE,

  PRIMARY KEY (id)
);