
CREATE SCHEMA schema_01;
SET SCHEMA schema_01;

CREATE TABLE schema_01.Parent (
  id INTEGER NOT NULL,
  COL2 CHAR(25),
  COL3 DECIMAL(10,2),
  COL4 VARCHAR(25),
  COL5 DATE,

  PRIMARY KEY (id),
  UNIQUE (COL3)
);

CREATE TABLE schema_01.Child (
  id INTEGER NOT NULL,
  Parent_id CHAR(25),
  COL3 DECIMAL(10,2),
  COL4 VARCHAR(25),
  COL5 DATE,

  PRIMARY KEY (id)
);

CREATE SCHEMA schema_02;
SET SCHEMA schema_02;

CREATE TABLE schema_02.Parent (
  id INTEGER NOT NULL,
  COL2 CHAR(25),
  COL3 DECIMAL(10,2),
  COL4 VARCHAR(25),
  COL5 DATE,

  PRIMARY KEY (id),
  UNIQUE (COL3)
);

CREATE TABLE schema_02.Child (
  id INTEGER NOT NULL,
  Parent_id CHAR(25),
  COL3 DECIMAL(10,2),
  COL4 VARCHAR(25),
  COL5 DATE,

  PRIMARY KEY (id)
);