package org.apache.cayenne.lifecycle.db.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.lifecycle.db.Auditable1;

/**
 * Class _AuditableChild2 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AuditableChild2 extends CayenneDataObject {

    public static final String CHAR_PROPERTY1_PROPERTY = "charProperty1";
    public static final String PARENT_PROPERTY = "parent";

    public static final String ID_PK_COLUMN = "ID";

    public void setCharProperty1(String charProperty1) {
        writeProperty(CHAR_PROPERTY1_PROPERTY, charProperty1);
    }
    public String getCharProperty1() {
        return (String)readProperty(CHAR_PROPERTY1_PROPERTY);
    }

    public void setParent(Auditable1 parent) {
        setToOneTarget(PARENT_PROPERTY, parent, true);
    }

    public Auditable1 getParent() {
        return (Auditable1)readProperty(PARENT_PROPERTY);
    }


}
