package org.apache.cayenne.lifecycle.db.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _E1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E1 extends CayenneDataObject {


    public static final String ID_PK_COLUMN = "ID";

}
