CREATE PROCEDURE cayenne_tst_upd_proc (IN painting_price INT)
	MODIFIES SQL DATA
	LANGUAGE SQL
BEGIN 
	UPDATE
	PAINTING SET ESTIMATED_PRICE = ESTIMATED_PRICE * 2 
	WHERE ESTIMATED_PRICE < painting_price;
	COMMIT;
END
