// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version
// 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0 Unless required by
// applicable law or agreed to in writing, software distributed under the
// License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for
// the specific language governing permissions and limitations under the
// License.

=== Expressions

Cayenne provides a simple, yet powerful, object-based expression language. The most common uses of expressions are to build qualifiers and orderings of queries that are later converted to SQL by Cayenne and to evaluate in-memory against specific objects (to access certain values in the object graph or to perform in-memory object filtering and sorting). Cayenne provides an API to build expressions in the code and a parser to create expressions from strings.

==== Path Expressions

Before discussing how to build expressions, it is important to understand one group of expressions widely used in Cayenne - path expressions. There are two types of path expressions - object and database, used for navigating graphs of connected objects or joined DB tables, respectively. Object paths are much more commonly used, as, after all, Cayenne is supposed to provide a degree of isolation of the object model from the database. However, database paths are helpful in certain situations. The general structure of path expressions is the following:

[source]
----
[db:]segment[+][#alias][.segment[+][#alias]...]
----

- `db:` is an optional prefix indicating that the following path is a DB path. Otherwise it is an object path.

- `segment` is a name of a property (relationship or attribute in Cayenne terms) in the path. The path must have at least one segment; segments are separated by dot (".").

- `#alias` is an optional alias of a relationship segment, discussed below.

- `+` An "OUTER JOIN" path component. Currently "+" only has effect when translated to SQL as OUTER JOIN. When evaluating expressions in memory, it is ignored.

An object path expression represents a chain of property names rooted in a certain (unspecified during expression creation) object and "navigating" to its related value.
E.g. a path expression "artist.name" might be a property path starting from a Painting object, pointing to the related Artist object, and then to its name attribute. A few more examples:

- `name` - can be used to navigate (read) the "name" property of a Person (or any other type of object that has a "name" property).

- `artist.exhibits.closingDate` - can be used to navigate to a closing date of any of the exhibits of a Painting's Artist object.

- `artist.exhibits+.closingDate` - same as the previous example, but when translated into SQL, an OUTER JOIN will be used for "exhibits".

Similarly a database path expression is a dot-separated path through DB table joins and columns.
In Cayenne joins are mapped as DbRelationships with some symbolic names (the closest concept to DbRelationship name in the DB world
is a named foreign key constraint. But DbRelationship names are usually chosen arbitrarily,
without regard to constraints naming or even constraints presence).
A database path therefore might look like this - `db:dbrelationshipX.dbrelationshipY.COLUMN_Z"`. More specific examples:

- `db:NAME` - can be used to navigate to a value in the "NAME" column of some unspecified table.

- `db:artist.artistExhibits.exhibit.CLOSING_DATE` - can be used to match a closing date of any of the exhibits of a related artist record.

Cayenne supports "aliases" in path expressions. An alias is appended to a relationship segment after the `#` character:

- `artist.exhibits.closingDate` - a path with no aliases

- `artist.exhibits#e.closingDate` - alias "e" is used for `artist.exhibits`.

The main use of aliases is to allow users to control how SQL joins are generated if the same path is encountered more than once in any given `Expression`. Each alias for any given path would result in a separate join. Without aliases, a single join will be used for a group of matching paths.

==== Creating Expressions from Strings

While in most cases users are likely to rely on the API from the following section for expression creation, we'll start by showing String expressions, as this will help you understand the semantics. A Cayenne expression can be represented as a String, which can be converted to an expression object using the `ExpressionFactory.exp` static method. Here is an example:


[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=exp]
----

This particular expression may be used to match Paintings whose names start with "A" and whose price is less than $1000. While this example is pretty self-explanatory, there are a few points worth mentioning. "name" and "price" here are object paths discussed earlier. As always, paths themselves are not attached to a specific root entity and can be applied to any entity that has similarly named attributes or relationships. So, when we say that this expression "may be used to match Paintings", we are implying that there may be other entities for which this expression is valid. Now the expression details...

Character constants that are not paths or numeric values should be enclosed in single or double quotes. Two of the expressions below are equivalent:

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=quotes]
----

Case sensitivity. Expression operators are case sensitive and are usually lowercase. Complex words follow the Java camel-case style:

[source]
----
include::{resource-examples}/expressions.txt[tags=case]
----

Grouping with parenthesis:


[source]
----
include::{resource-examples}/expressions.txt[tags=grouping]
----

Path prefixes. Object expressions are unquoted strings, optionally prefixed by `obj:` (usually they are not prefixed at all).
Database expressions are always prefixed with `db:`. A special kind of prefix, not discussed yet, is `enum:` that prefixes an enumeration constant:

[source]
----
include::{resource-examples}/expressions.txt[tags=paths]
----

Binary conditions are expressions that contain a path on the left, a value on the right, and some operation between them, such as equals like, etc. They can be used as qualifiers in SelectQueries:

[source]
----
include::{resource-examples}/expressions.txt[tags=like]
----


Parameters. Expressions can contain named parameters (names that start with "$") that can be substituted with values either by name or by position. Parameterized expressions let you create reusable expression templates. Also, if an expression contains a complex object that doesn’t have a simple String representation (e.g. a `Date`, a `Persistent`, an `ObjectId`), parameterizing the expression is the only way to represent it as String. Here are examples of both positional and named parameter bindings:

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=params]
----

Positional binding is usually shorter. You can pass positional bindings to the `exp(..)` factory method (its second argument is a params vararg):

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=expWithParams]
----

In parameterized expressions with a LIKE clause, SQL wildcards must be part of the values in the Map and not the expression string itself:

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=likeParam]
----

When matching on a relationship, the value parameter must be either a Persistent object, an `org.apache.cayenne.ObjectId`, or a numeric ID value (for single column IDs). E.g.:

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=objectParam]
----

When you use positional binding, Cayenne expects values for all parameters to be present. Binding by name offers extra flexibility: sub-expressions with uninitialized parameters are automatically pruned from the expression. So, e.g., if certain parts of the expression criteria are not provided to the application, you can still build a valid expression


[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=pruning]
----

Null handling. Handling of Java nulls as operands is no different handling from normal values. Instead of using special conditional operators, like SQL does (`IS NULL`, `IS NOT NULL`), "=" and "!=" expressions are used directly with null values. It is up to Cayenne to translate expressions with nulls to the valid SQL.

//NOTE: A formal definition of the expression grammar is provided in xref:appendixC[Appendix C]

==== Creating Expressions via API

Creating expressions from Strings is a powerful and dynamic approach, however a safer alternative is to use the Java API. It provides compile-time checking of the expression's validity. The API in question is provided by the `ExpressionFactory` class (that we've seen already), the Property class and the Expression class itself. `ExpressionFactory` contains a number of self-explanatory static methods that can be used to build expressions. E.g.:

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=expressionFactory]
----

NOTE: The last line in the example above shows how to create a new expression by "chaining" two other expressions. A common error when chaining expressions is to assume that "andExp" and "orExp" append another expression to the current expression. In fact, a new expression is created. Expression API treats existing expressions as immutable.

As discussed earlier, Cayenne supports aliases in path Expressions, so you can control how SQL joins are generated if the same path is encountered more than once in the same Expression. Two `ExpressionFactory.matchAllExp(..)` methods (one taking a `Collection` of values, another - a vararg) let you implicitly generate aliases to "split" match paths into individual joins if needed:

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=matchAllExp]
----

The "Path" argument to both of these methods can use a split character (a pipe symbol '|') instead of a dot to indicate that the relationship following a path should be split into a separate set of joins, one per collection value. There can only be one split at most in any given path. The split must always precede a relationship. E.g. `"|exhibits.paintings"`, `"exhibits|paintings"`, etc. Internally, Cayenne generates distinct aliases for each of the split expressions, forcing separate joins.

While ExpressionFactory is pretty powerful, there's an even easier way to create an expression using static Property objects generated by Cayenne for each persistent class.
Some examples:

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=properties]
----

Property objects provide the API mostly analogous to ExpressionFactory, though it is significantly shorter and is aware of the value types.
It provides compile-time checks of both property names and types of arguments in conditions. We will use Property-based API in further examples.

[[evaluate]]
==== Evaluating Expressions in Memory

When used in a query, an expression is converted to a SQL WHERE or ORDER BY clause by Cayenne during query execution. Thus the actual evaluation against the data is done by the database engine. However, the same expressions can also be used for accessing object properties, calculating values, and in-memory filtering.


Checking whether an object satisfies an expression:

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=match]
----

Reading property value:


[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=evaluate]
----

Filtering a list of objects:

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=filterObjects]
----


NOTE: Current limitation of in-memory expressions is that no collections are permitted in the property path.

==== Translating Expressions to EJBQL

<<ejbql,EJBQL>> is a textual query language that can be used with Cayenne. In some situations,
it is convenient to be able to convert Expression instances into EJBQL. Expressions support this conversion. An example is shown below.

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=toEJBQL]
----

This would be equivalent to the following purely EJBQL querying logic;

[source,java,indent=0]
----
include::{java-examples}/ExpressionsTest.java[tags=ejbql]
----

