package org.apache.cayenne.testdo.testmap.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.testmap.Bag;
import org.apache.cayenne.testdo.testmap.Ball;
import org.apache.cayenne.testdo.testmap.BoxInfo;
import org.apache.cayenne.testdo.testmap.Thing;

/**
 * Class _Box was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Box extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String NAME_PROPERTY = "name";
    @Deprecated
    public static final String BAG_PROPERTY = "bag";
    @Deprecated
    public static final String BALLS_PROPERTY = "balls";
    @Deprecated
    public static final String BOX_INFO_PROPERTY = "boxInfo";
    @Deprecated
    public static final String THINGS_PROPERTY = "things";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<Bag> BAG = new Property<Bag>("bag");
    public static final Property<List<Ball>> BALLS = new Property<List<Ball>>("balls");
    public static final Property<BoxInfo> BOX_INFO = new Property<BoxInfo>("boxInfo");
    public static final Property<List<Thing>> THINGS = new Property<List<Thing>>("things");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setBag(Bag bag) {
        setToOneTarget("bag", bag, true);
    }

    public Bag getBag() {
        return (Bag)readProperty("bag");
    }


    public void addToBalls(Ball obj) {
        addToManyTarget("balls", obj, true);
    }
    public void removeFromBalls(Ball obj) {
        removeToManyTarget("balls", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Ball> getBalls() {
        return (List<Ball>)readProperty("balls");
    }


    public void setBoxInfo(BoxInfo boxInfo) {
        setToOneTarget("boxInfo", boxInfo, true);
    }

    public BoxInfo getBoxInfo() {
        return (BoxInfo)readProperty("boxInfo");
    }


    @SuppressWarnings("unchecked")
    public List<Thing> getThings() {
        return (List<Thing>)readProperty("things");
    }


}
