package org.apache.cayenne.testdo.testmap.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.testdo.testmap.Bag;
import org.apache.cayenne.testdo.testmap.Ball;
import org.apache.cayenne.testdo.testmap.BoxInfo;
import org.apache.cayenne.testdo.testmap.Thing;

/**
 * Class _Box was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Box extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String BAG_PROPERTY = "bag";
    public static final String BALLS_PROPERTY = "balls";
    public static final String BOX_INFO_PROPERTY = "boxInfo";
    public static final String THINGS_PROPERTY = "things";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setBag(Bag bag) {
        setToOneTarget(BAG_PROPERTY, bag, true);
    }

    public Bag getBag() {
        return (Bag)readProperty(BAG_PROPERTY);
    }


    public void addToBalls(Ball obj) {
        addToManyTarget(BALLS_PROPERTY, obj, true);
    }
    public void removeFromBalls(Ball obj) {
        removeToManyTarget(BALLS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Ball> getBalls() {
        return (List<Ball>)readProperty(BALLS_PROPERTY);
    }


    public void setBoxInfo(BoxInfo boxInfo) {
        setToOneTarget(BOX_INFO_PROPERTY, boxInfo, true);
    }

    public BoxInfo getBoxInfo() {
        return (BoxInfo)readProperty(BOX_INFO_PROPERTY);
    }


    @SuppressWarnings("unchecked")
    public List<Thing> getThings() {
        return (List<Thing>)readProperty(THINGS_PROPERTY);
    }


}
