package org.apache.cayenne.testdo.testmap.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _CharacterEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CharacterEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String CHARACTER_FIELD_PROPERTY = "characterField";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Character> CHARACTER_FIELD = new Property<Character>("characterField");

    public void setCharacterField(Character characterField) {
        writeProperty("characterField", characterField);
    }
    public Character getCharacterField() {
        return (Character)readProperty("characterField");
    }

}
