package org.apache.cayenne.testdo.testmap.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.testdo.testmap.Artist;
import org.apache.cayenne.testdo.testmap.Gallery;
import org.apache.cayenne.testdo.testmap.PaintingInfo;
import org.apache.cayenne.testdo.testmap.ROArtist;

/**
 * Class _CompoundPaintingLongNames was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CompoundPaintingLongNames extends CayenneDataObject {

    public static final String ARTIST_LONG_NAME_PROPERTY = "artistLongName";
    public static final String ESTIMATED_PRICE_PROPERTY = "estimatedPrice";
    public static final String GALLERY_LONG_NAME_PROPERTY = "galleryLongName";
    public static final String PAINTING_DESCRIPTION_PROPERTY = "paintingDescription";
    public static final String PAINTING_TITLE_PROPERTY = "paintingTitle";
    public static final String TEXT_LONG_REVIEW_PROPERTY = "textLongReview";
    public static final String TO_ARTIST_PROPERTY = "toArtist";
    public static final String TO_ARTIST1_PROPERTY = "toArtist1";
    public static final String TO_GALLERY_PROPERTY = "toGallery";
    public static final String TO_PAINTING_INFO_PROPERTY = "toPaintingInfo";

    public static final String PAINTING_ID_PK_COLUMN = "PAINTING_ID";

    public void setArtistLongName(String artistLongName) {
        writeProperty("artistLongName", artistLongName);
    }
    public String getArtistLongName() {
        return (String)readProperty("artistLongName");
    }

    public void setEstimatedPrice(BigDecimal estimatedPrice) {
        writeProperty("estimatedPrice", estimatedPrice);
    }
    public BigDecimal getEstimatedPrice() {
        return (BigDecimal)readProperty("estimatedPrice");
    }

    public void setGalleryLongName(String galleryLongName) {
        writeProperty("galleryLongName", galleryLongName);
    }
    public String getGalleryLongName() {
        return (String)readProperty("galleryLongName");
    }

    public void setPaintingDescription(String paintingDescription) {
        writeProperty("paintingDescription", paintingDescription);
    }
    public String getPaintingDescription() {
        return (String)readProperty("paintingDescription");
    }

    public void setPaintingTitle(String paintingTitle) {
        writeProperty("paintingTitle", paintingTitle);
    }
    public String getPaintingTitle() {
        return (String)readProperty("paintingTitle");
    }

    public void setTextLongReview(String textLongReview) {
        writeProperty("textLongReview", textLongReview);
    }
    public String getTextLongReview() {
        return (String)readProperty("textLongReview");
    }

    public void setToArtist(Artist toArtist) {
        setToOneTarget("toArtist", toArtist, true);
    }

    public Artist getToArtist() {
        return (Artist)readProperty("toArtist");
    }


    public void setToArtist1(ROArtist toArtist1) {
        setToOneTarget("toArtist1", toArtist1, true);
    }

    public ROArtist getToArtist1() {
        return (ROArtist)readProperty("toArtist1");
    }


    public void setToGallery(Gallery toGallery) {
        setToOneTarget("toGallery", toGallery, true);
    }

    public Gallery getToGallery() {
        return (Gallery)readProperty("toGallery");
    }


    public void setToPaintingInfo(PaintingInfo toPaintingInfo) {
        setToOneTarget("toPaintingInfo", toPaintingInfo, true);
    }

    public PaintingInfo getToPaintingInfo() {
        return (PaintingInfo)readProperty("toPaintingInfo");
    }


}
