package org.apache.cayenne.testdo.testmap.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ReturnTypesMap was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ReturnTypesMap2 extends CayenneDataObject {

    public static final String BINARY_COLUMN_PROPERTY = "binaryColumn";
    public static final String BLOB_COLUMN_PROPERTY = "blobColumn";
    public static final String LONGVARBINARY_COLUMN_PROPERTY = "longvarbinaryColumn";
    public static final String VARBINARY_COLUMN_PROPERTY = "varbinaryColumn";

    public static final String AAAID_PK_COLUMN = "AAAID";

    public void setBinaryColumn(byte[] binaryColumn) {
        writeProperty("binaryColumn", binaryColumn);
    }
    public byte[] getBinaryColumn() {
        return (byte[])readProperty("binaryColumn");
    }

    public void setBlobColumn(byte[] blobColumn) {
        writeProperty("blobColumn", blobColumn);
    }
    public byte[] getBlobColumn() {
        return (byte[])readProperty("blobColumn");
    }

    public void setLongvarbinaryColumn(byte[] longvarbinaryColumn) {
        writeProperty("longvarbinaryColumn", longvarbinaryColumn);
    }
    public byte[] getLongvarbinaryColumn() {
        return (byte[])readProperty("longvarbinaryColumn");
    }

    public void setVarbinaryColumn(byte[] varbinaryColumn) {
        writeProperty("varbinaryColumn", varbinaryColumn);
    }
    public byte[] getVarbinaryColumn() {
        return (byte[])readProperty("varbinaryColumn");
    }

}
