package org.apache.cayenne.testdo.testmap.auto;

import java.util.UUID;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _UuidTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UuidTestEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String UUID_PROPERTY = "uuid";

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<UUID> UUID = new Property<UUID>("uuid");

    public void setUuid(UUID uuid) {
        writeProperty("uuid", uuid);
    }
    public UUID getUuid() {
        return (UUID)readProperty("uuid");
    }

}
