package org.apache.cayenne.testdo.testmap.auto;

import java.util.UUID;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _UuidPkEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UuidPkEntity extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";

    public static final String ID_PK_COLUMN = "ID";

    public void setId(UUID id) {
        writeProperty(ID_PROPERTY, id);
    }
    public UUID getId() {
        return (UUID)readProperty(ID_PROPERTY);
    }

}
